project:
  type: website
  output-dir: docs

website:
  title: "Journal Club"
  search: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Articles
        menu:
          - href: post/260423/nonspecific_cellular_interactions_are.qmd
            text: "Fc-Fused Proteins Disposition (EN)"
          - href: post/260423/nonspecific_cellular_interactions_are_ko.qmd
            text: "Fc-Fused Proteins Disposition (KO)"
      - about.qmd

format:
  html:
    theme:
      - flatly
      - brand
    css: styles.css
    toc: true

execute:
  freeze: auto
