<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Mark A. Bryniarski, Songyu Wang, Aochiu Chen, Brian Coventry, Elif Nihal Korkmaz, Md Tariqul Haque Tuhin, Eunkyung Clare Ko, Devin L. Wakefield, Edward L. LaGory, Hao Wu, Achala Punchi Hewage, Khue Dang, Marcus Soto, Manuel Ponce, Esperanza Ojeda, Kip P. Conner, Lance J. Stewart, Christine E. Tinberg, Ai Ching Lim, David Baker, and Kevin D. Cook">
<meta name="dcterms.date" content="2026-04-23">
<meta name="description" content="Fc 융합 단백질의 체내 소실에 관여하는 핵심 물리화학적 속성 및 세포 내 기전 연구">

<title>비특이적 세포 상호작용: Fc 융합 단백질의 체내 소실을 결정하는 핵심 요인 – Journal Club</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-f7919f14b89ae9a431cba0b331f0b52b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Journal Club</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#서론" id="toc-서론" class="nav-link active" data-scroll-target="#서론">서론</a></li>
  <li><a href="#재료-및-방법" id="toc-재료-및-방법" class="nav-link" data-scroll-target="#재료-및-방법">재료 및 방법</a>
  <ul class="collapse">
  <li><a href="#세포-배양" id="toc-세포-배양" class="nav-link" data-scroll-target="#세포-배양">세포 배양</a></li>
  <li><a href="#단백질-설계" id="toc-단백질-설계" class="nav-link" data-scroll-target="#단백질-설계">단백질 설계</a></li>
  <li><a href="#플라스미드" id="toc-플라스미드" class="nav-link" data-scroll-target="#플라스미드">플라스미드</a></li>
  <li><a href="#포유류-발현" id="toc-포유류-발현" class="nav-link" data-scroll-target="#포유류-발현">포유류 발현</a></li>
  <li><a href="#재조합-단백질-정제" id="toc-재조합-단백질-정제" class="nav-link" data-scroll-target="#재조합-단백질-정제">재조합 단백질 정제</a></li>
  <li><a href="#분석용-sec" id="toc-분석용-sec" class="nav-link" data-scroll-target="#분석용-sec">분석용 SEC</a></li>
  <li><a href="#lc-ms를-이용한-온전한-질량-분석" id="toc-lc-ms를-이용한-온전한-질량-분석" class="nav-link" data-scroll-target="#lc-ms를-이용한-온전한-질량-분석">LC-MS를 이용한 온전한 질량 분석</a></li>
  <li><a href="#엔도톡신-측정" id="toc-엔도톡신-측정" class="nav-link" data-scroll-target="#엔도톡신-측정">엔도톡신 측정</a></li>
  <li><a href="#미세-모세관-전기영동mce" id="toc-미세-모세관-전기영동mce" class="nav-link" data-scroll-target="#미세-모세관-전기영동mce">미세 모세관 전기영동(MCE)</a></li>
  <li><a href="#단백질-특성의-인-실리코-계산" id="toc-단백질-특성의-인-실리코-계산" class="nav-link" data-scroll-target="#단백질-특성의-인-실리코-계산">단백질 특성의 인 실리코 계산</a></li>
  <li><a href="#혈청-농도-약동학-연구" id="toc-혈청-농도-약동학-연구" class="nav-link" data-scroll-target="#혈청-농도-약동학-연구">혈청 농도 약동학 연구</a></li>
  <li><a href="#생체-분포-연구" id="toc-생체-분포-연구" class="nav-link" data-scroll-target="#생체-분포-연구">생체 분포 연구</a></li>
  <li><a href="#마우스-혈청-및-조직-내-fc-융합-단백질-농도-정량" id="toc-마우스-혈청-및-조직-내-fc-융합-단백질-농도-정량" class="nav-link" data-scroll-target="#마우스-혈청-및-조직-내-fc-융합-단백질-농도-정량">마우스 혈청 및 조직 내 Fc 융합 단백질 농도 정량</a></li>
  <li><a href="#cho-k1-nse-측정" id="toc-cho-k1-nse-측정" class="nav-link" data-scroll-target="#cho-k1-nse-측정">CHO-K1 NSE 측정</a></li>
  <li><a href="#fc-융합-단백질의-인간-fcrn-재활용-연구" id="toc-fc-융합-단백질의-인간-fcrn-재활용-연구" class="nav-link" data-scroll-target="#fc-융합-단백질의-인간-fcrn-재활용-연구">Fc 융합 단백질의 인간 FcRn 재활용 연구</a></li>
  <li><a href="#mesoscale-discovery-면역-분석법에-의한-세포-hfcrn-재활용-분석-샘플-분석" id="toc-mesoscale-discovery-면역-분석법에-의한-세포-hfcrn-재활용-분석-샘플-분석" class="nav-link" data-scroll-target="#mesoscale-discovery-면역-분석법에-의한-세포-hfcrn-재활용-분석-샘플-분석">MesoScale Discovery 면역 분석법에 의한 세포 hFcRn 재활용 분석 샘플 분석</a></li>
  <li><a href="#인간-frem-점수" id="toc-인간-frem-점수" class="nav-link" data-scroll-target="#인간-frem-점수">인간 FREM 점수</a></li>
  <li><a href="#단백질의-플루오레세인-이소티오시아네이트fitc-및-dylightdl-650-표지" id="toc-단백질의-플루오레세인-이소티오시아네이트fitc-및-dylightdl-650-표지" class="nav-link" data-scroll-target="#단백질의-플루오레세인-이소티오시아네이트fitc-및-dylightdl-650-표지">단백질의 플루오레세인 이소티오시아네이트(FITC) 및 Dylight(DL) 650 표지</a></li>
  <li><a href="#이미지화된-모세관-등전점-전기영동icief-분석" id="toc-이미지화된-모세관-등전점-전기영동icief-분석" class="nav-link" data-scroll-target="#이미지화된-모세관-등전점-전기영동icief-분석">이미지화된 모세관 등전점 전기영동(icIEF) 분석</a></li>
  <li><a href="#미세-유체-장치-내-미세-혈관-네트워크mvn-형성" id="toc-미세-유체-장치-내-미세-혈관-네트워크mvn-형성" class="nav-link" data-scroll-target="#미세-유체-장치-내-미세-혈관-네트워크mvn-형성">미세 유체 장치 내 미세 혈관 네트워크(MVN) 형성</a></li>
  <li><a href="#mvn-내-정점-기저부-단백질-투과성-이미징" id="toc-mvn-내-정점-기저부-단백질-투과성-이미징" class="nav-link" data-scroll-target="#mvn-내-정점-기저부-단백질-투과성-이미징">MVN 내 정점-기저부 단백질 투과성 이미징</a></li>
  <li><a href="#mvn-내-단백질-투과성-이미지-분석" id="toc-mvn-내-단백질-투과성-이미지-분석" class="nav-link" data-scroll-target="#mvn-내-단백질-투과성-이미지-분석">MVN 내 단백질 투과성 이미지 분석</a></li>
  <li><a href="#미세-유체-장치-내-인-비트로-간질-상호작용-측정" id="toc-미세-유체-장치-내-인-비트로-간질-상호작용-측정" class="nav-link" data-scroll-target="#미세-유체-장치-내-인-비트로-간질-상호작용-측정">미세 유체 장치 내 인 비트로 간질 상호작용 측정</a></li>
  </ul></li>
  <li><a href="#결과" id="toc-결과" class="nav-link" data-scroll-target="#결과">결과</a>
  <ul class="collapse">
  <li><a href="#다양한-물리화학적-속성을-가진-fc-융합-단백질-패널의-설계-및-생산" id="toc-다양한-물리화학적-속성을-가진-fc-융합-단백질-패널의-설계-및-생산" class="nav-link" data-scroll-target="#다양한-물리화학적-속성을-가진-fc-융합-단백질-패널의-설계-및-생산">다양한 물리화학적 속성을 가진 Fc 융합 단백질 패널의 설계 및 생산</a></li>
  <li><a href="#인-실리코-전하-기술자는-야생형-마우스에서의-제거율과-가장-강력하게-상관관계를-나타낸다" id="toc-인-실리코-전하-기술자는-야생형-마우스에서의-제거율과-가장-강력하게-상관관계를-나타낸다" class="nav-link" data-scroll-target="#인-실리코-전하-기술자는-야생형-마우스에서의-제거율과-가장-강력하게-상관관계를-나타낸다">인 실리코 전하 기술자는 야생형 마우스에서의 제거율과 가장 강력하게 상관관계를 나타낸다</a></li>
  <li><a href="#상대적인-알짜-전하-극단은-cl-증가-및-조직-축적-상승과-연관되어-있다" id="toc-상대적인-알짜-전하-극단은-cl-증가-및-조직-축적-상승과-연관되어-있다" class="nav-link" data-scroll-target="#상대적인-알짜-전하-극단은-cl-증가-및-조직-축적-상승과-연관되어-있다">상대적인 알짜 전하 극단은 CL 증가 및 조직 축적 상승과 연관되어 있다</a></li>
  <li><a href="#fc-융합체의-cl을-결정하는-세포-과정에서-전하의-역할" id="toc-fc-융합체의-cl을-결정하는-세포-과정에서-전하의-역할" class="nav-link" data-scroll-target="#fc-융합체의-cl을-결정하는-세포-과정에서-전하의-역할">Fc 융합체의 CL을 결정하는 세포 과정에서 전하의 역할</a></li>
  <li><a href="#fc-융합체의-비표적-조직-축적에서-전하의-역할" id="toc-fc-융합체의-비표적-조직-축적에서-전하의-역할" class="nav-link" data-scroll-target="#fc-융합체의-비표적-조직-축적에서-전하의-역할">Fc 융합체의 비표적 조직 축적에서 전하의 역할</a></li>
  <li><a href="#리포좀-클로드로네이트를-통한-대식세포-고갈은-lcb1-fc-융합-단백질의-비장-축적-증가를-초래한다" id="toc-리포좀-클로드로네이트를-통한-대식세포-고갈은-lcb1-fc-융합-단백질의-비장-축적-증가를-초래한다" class="nav-link" data-scroll-target="#리포좀-클로드로네이트를-통한-대식세포-고갈은-lcb1-fc-융합-단백질의-비장-축적-증가를-초래한다">리포좀 클로드로네이트를 통한 대식세포 고갈은 LCB1 Fc 융합 단백질의 비장 축적 증가를 초래한다</a></li>
  </ul></li>
  <li><a href="#고찰" id="toc-고찰" class="nav-link" data-scroll-target="#고찰">고찰</a></li>
  <li><a href="#결론" id="toc-결론" class="nav-link" data-scroll-target="#결론">결론</a></li>
  <li><a href="#관련-콘텐츠" id="toc-관련-콘텐츠" class="nav-link" data-scroll-target="#관련-콘텐츠">관련 콘텐츠</a>
  <ul class="collapse">
  <li><a href="#지원-정보" id="toc-지원-정보" class="nav-link" data-scroll-target="#지원-정보">지원 정보</a></li>
  </ul></li>
  <li><a href="#참고-문헌" id="toc-참고-문헌" class="nav-link" data-scroll-target="#참고-문헌">참고 문헌</a></li>
  <li><a href="#지원-정보-1" id="toc-지원-정보-1" class="nav-link" data-scroll-target="#지원-정보-1">지원 정보</a>
  <ul class="collapse">
  <li><a href="#지원-표-1.-fc-융합-단백질의-분석-요약" id="toc-지원-표-1.-fc-융합-단백질의-분석-요약" class="nav-link" data-scroll-target="#지원-표-1.-fc-융합-단백질의-분석-요약">지원 표 1. Fc 융합 단백질의 분석 요약</a></li>
  <li><a href="#지원-표-2.-마우스-제거율-대비-인-실리코-및-인-비트로-파라미터의-스피어만-상관관계-매트릭스-및-해당-p-값" id="toc-지원-표-2.-마우스-제거율-대비-인-실리코-및-인-비트로-파라미터의-스피어만-상관관계-매트릭스-및-해당-p-값" class="nav-link" data-scroll-target="#지원-표-2.-마우스-제거율-대비-인-실리코-및-인-비트로-파라미터의-스피어만-상관관계-매트릭스-및-해당-p-값">지원 표 2. 마우스 제거율 대비 인 실리코 및 인 비트로 파라미터의 스피어만 상관관계 매트릭스 및 해당 p 값</a></li>
  <li><a href="#지원-그림-2-cho-k1-세포내섭취는-테스트된-모든-단백질-모달리티에서-ph-의존적이다." id="toc-지원-그림-2-cho-k1-세포내섭취는-테스트된-모든-단백질-모달리티에서-ph-의존적이다." class="nav-link" data-scroll-target="#지원-그림-2-cho-k1-세포내섭취는-테스트된-모든-단백질-모달리티에서-ph-의존적이다.">지원 그림 2: CHO-K1 세포내섭취는 테스트된 모든 단백질 모달리티에서 pH 의존적이다.</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">비특이적 세포 상호작용: Fc 융합 단백질의 체내 소실을 결정하는 핵심 요인</h1>
  <div class="quarto-categories">
    <div class="quarto-category">약동학</div>
    <div class="quarto-category">Fc 융합 단백질</div>
    <div class="quarto-category">단백질 공학</div>
  </div>
  </div>

<div>
  <div class="description">
    Fc 융합 단백질의 체내 소실에 관여하는 핵심 물리화학적 속성 및 세포 내 기전 연구
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Mark A. Bryniarski, Songyu Wang, Aochiu Chen, Brian Coventry, Elif Nihal Korkmaz, Md Tariqul Haque Tuhin, Eunkyung Clare Ko, Devin L. Wakefield, Edward L. LaGory, Hao Wu, Achala Punchi Hewage, Khue Dang, Marcus Soto, Manuel Ponce, Esperanza Ojeda, Kip P. Conner, Lance J. Stewart, Christine E. Tinberg, Ai Ching Lim, David Baker, and Kevin D. Cook </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">April 23, 2026</p>
    </div>
  </div>
  
    
  </div>
  
<div>
  <div class="abstract">
    <div class="block-title">Abstract</div>
    <p>치료용 단백질 구조가 점차 다양해짐에 따라, 이들의 약동학적(pharmacokinetic) 특성을 결정하는 기전을 파악하는 것이 매우 중요해졌습니다. 본 연구는 Fc(fragment crystallizable) 영역을 포함하는 단백질의 표적 독립적 소실(target-independent disposition)에 영향을 미치는 주요 물리화학적 속성과 세포 내 과정을 규명하고자 수행되었습니다. 연구팀은 마우스 내 결합 파트너가 없는 5종의 데 노보(de novo) 설계 단백질 스캐폴드를 기반으로 표면 특성을 체계적으로 재설계하여, 각기 다른 물리화학적 특성을 지닌 총 35종의 Fc 융합 단백질을 제작했습니다. 야생형 마우스를 대상으로 한 약동학 연구 결과, 단백질마다 제거율(elimination rates)과 조직 축적 정도에서 현저한 차이가 나타났으며, 이는 전하 기술자(charge descriptors)와 가장 밀접한 연관성을 보였습니다. 일련의 인 비트로(in vitro) 실험을 통해 이러한 인 비보(in vivo) 관찰 결과가 세포 비특이성(cellular nonspecificity)과 유의미한 상관관계가 있음을 입증하였습니다. 특히 표면의 양전하는 비특이적 흡착 세포내섭취(nonspecific adsorptive endocytosis)를 촉진하고 신생아 Fc 수용체(FcRn)에 의한 재활용 효율을 떨어뜨려, 결과적으로 세포 내 순 축적을 유발하는 것으로 나타났습니다. 결론적으로 본 연구는 Fc 융합 단백질의 소실이 전하에 의해 조절되는 상세 기전을 제시하며, 향후 약동학적 프로파일이 최적화된 단백질 공학적 설계에 중요한 가이드라인을 제공할 것입니다.</p>
  </div>
</div>


</header>


<p><img src="images/86fbd11842e8094367259a820a7f027fe9a6f0947826d0b5c07c638717a84a74.jpg" class="img-fluid"></p>
<section id="서론" class="level1">
<h1>서론</h1>
<p>바이오 의약품 산업은 IgG 기반 단일클론 항체(mAbs)의 성공을 발판 삼아, 혁신적인 치료 전략을 구현하기 위해 항체 기반 단백질 모달리티(modality)를 지속적으로 확장해 왔습니다.[^1-6] 이러한 흐름은 계산 과학 기반의 미니 단백질(miniproteins) 설계 기술과 결합하여 표적 결합의 새로운 지평을 열고 있습니다.[^7-9] 다만, 새로운 분자 형태를 설계할 때는 약리학적 효능뿐만 아니라 실제 의약품 생산을 위한 제조 가능성(developability) 사이의 적절한 균형이 반드시 고려되어야 합니다.[^10-20] 특히 신약 발견 및 최적화 단계에서는 약동학(PK) 매개변수로 설명되는 분포, 대사, 제거 등 유리한 체내 소실 특성을 확보하는 것이 핵심입니다. 이는 임상적 효능을 발휘하기 위해 체내에서 충분한 약물 노출량을 유지하는 데 필수적이기 때문입니다. 따라서 전임상 후보 물질의 설계를 개선하고 고도화하기 위해서는 치료용 단백질의 소실을 결정하는 요인들에 대한 깊은 기전적 이해가 선행되어야 합니다.[^21-22]</p>
<p>단일클론 항체가 효과적인 치료제로 자리 잡은 주요 이유 중 하나는 크기가 유사한 다른 단백질에 비해 표적 독립적 제거율이 낮다는 점입니다.[^23-24] 이러한 긴 반감기는 주로 Fc 영역이 신생아 Fc 수용체(FcRn, FCGRT) 및 <span class="math inline">\(\beta 2\)</span>-마이크로글로불린(B2M)과 pH 의존적으로 상호작용하면서 나타납니다. 일반적으로 비특이적으로 내부화된 단백질은 리소좀에서 이화작용(lysosomal catabolism)을 거쳐 사라지게 됩니다.[^25-27] 하지만 세포 내로 섭취된 항체는 소낭 구획 내의 산성 pH 환경에서 FcRn과 높은 친화력으로 결합합니다.[^24-32] 이후 FcRn은 항체를 세포 표면으로 다시 운반하여 중성 pH 환경에서 방출(재활용)하거나 세포를 통과시키는 가로세포흐름(transcytose)을 유도합니다. 이처럼 비표적 제거를 억제할 수 있는 경로를 활용하기 위해 많은 치료용 단백질이나 펩타이드에 Fc 도메인을 통합하고 있습니다.[^22-24]</p>
<p>전임상 및 임상 단계의 항체들은 FcRn 결합력 차이만으로는 설명하기 어려운 매우 다양한 표적 독립적 제거율 <span class="math inline">\(\mathrm{(CL_{ind})}\)</span>을 보입니다.[^22-33] 이에 따라 항체 간 소실 특성의 차이를 유발하는 물리화학적 요인을 규명하려는 연구가 활발히 진행되어 왔습니다.[^10-35] 그중에서도 ’전하’는 약물의 제거 및 분포 이상과 밀접하게 연관된 핵심 속성으로 꼽힙니다. 대체로 음전하나 양전하가 과도한 항체는 <span class="math inline">\(\mathrm{CL}_{\mathrm{ind}}\)</span>가 더 빠르고 비표적 조직 축적이 광범위하게 나타나는 경향이 있습니다.[^12-16][^18-43] 특히 본 연구팀을 포함한 여러 연구자들은 단순히 알짜 전하(net charge)뿐만 아니라 분포 패턴과 크기를 포함한 ’표면 전하 특성’이 비특이적 세포내섭취(NSE), FcRn 상호작용 및 일반적인 세포 비특이성을 변화시켜 항체의 <span class="math inline">\(\mathrm{CL}_{\mathrm{ind}}\)</span>에 상당한 영향을 미칠 수 있음을 입증한 바 있습니다.[^38-47] 용매에 노출된 양전하와 음전하를 띤 세포막 사이의 상호작용 방식에 따라 항체마다 NSE 속도가 크게 달라질 수 있으며, 이는 표적이 없는 세포에서도 높은 수준의 내부화를 유발합니다.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> 또한 이러한 표면 전하의 불균형은 FcRn과의 pH 의존적 결합을 방해하여, 리소좀으로 향하는 분율을 높이고 재활용 효율을 떨어뜨림으로써 항체의 이화작용을 가속화합니다.[^45-46]</p>
<p>이러한 선행 연구들은 물리화학적 특성이 치료용 항체의 성공 여부에 얼마나 큰 영향을 미치는지 잘 보여줍니다. 하지만 여전히 일반적인 경향성에서 벗어나는 사례가 빈번하게 발생합니다. 예를 들어 전하 기술자만으로는 높은 <span class="math inline">\(\mathrm{CL}_{\mathrm{ind}}\)</span>나 조직 축적 현상을 완벽히 설명하지 못하는 경우가 많으며, 상관관계가 거의 없는 것으로 보고된 연구도 존재합니다.[^35-49] 즉, 물리화학적 속성과 제거·분포 사이의 관계를 규정하는 정확한 생리학적·세포적 기전은 아직 완전히 정의되지 않았습니다. 따라서 어떤 속성이 소실 위험을 높이는지 식별하고 그 기전적 근거를 이해하는 것은 Fc 기반 치료제의 제조 가능성을 높이는 데 매우 중요합니다. 아울러 이러한 PK 중심의 평가를 항체 외의 모달리티, 특히 아미노산 조성을 정밀하게 제어할 수 있는 데 노보 스캐폴드 영역으로 확장할 필요가 있습니다.[^7-9] 서열 재설계와 Fc 도메인 융합이 스캐폴드의 체내 거동에 미치는 영향을 규명한다면, 최적의 PK 특성을 설계하는 데 매우 유익한 정보를 얻을 수 있을 것입니다.</p>
<p>본 연구에서는 내인성 항원 결합이 배제된 상태에서 다양한 크기, 형태, 물리화학적 특성을 지닌 설계 단백질 패널의 PK 속성을 체계적으로 조사하였습니다. 이를 통해 소실 위험을 결정하는 주요 표적 독립적 요인들을 더 깊이 이해하고자 하였습니다. 연구팀은 서로 다른 크기와 토폴로지(topology)를 가진 5종의 데 노보 단백질을 선정하고, 고유의 폴딩 구조를 유지하면서도 표면 특성이 각기 다른 변이체들을 설계하였습니다. 제작된 Fc 융합 단백질의 PK 연구 결과, 표면 전하가 체내 소실의 결정적 요인임을 확인하였으며, 광범위한 인 비트로 실험을 통해 이러한 인 비보 관찰 결과를 뒷받침하는 세포 내 기본 기전을 확립하였습니다.</p>
</section>
<section id="재료-및-방법" class="level1">
<h1>재료 및 방법</h1>
<section id="세포-배양" class="level2">
<h2 class="anchored" data-anchor-id="세포-배양">세포 배양</h2>
<p>NSE 분석용 CHO-K1 세포는 Amgen 내부에서 확보하였으며, <span class="math inline">\(10\%\)</span> 열 불활성화 태아 혈청(#16140071, Thermo)을 포함한 Ham’s F-12K 배지(no. 21127022, Thermo Fisher, Waltham, MA)에서 배양하였습니다. 최적의 계대 배양 조건은 2~3일마다 <span class="math inline">\(\mathrm{cm}^2\)</span> 당 <span class="math inline">\(1.5 \sim 2.0 \times 10^{4}\)</span> cells로 유지하였습니다. 인간 제대 정맥 내피 세포(HUVECs)는 GFP 발현 라인(#cAP-0001GFP, Angioprotomie, Boston, MA)과 야생형 라인(#CC-2519, Lonza, Walkersville, MD)을 사용하였습니다. 미세 유체 칩 시딩 전까지 VascuLife VEGF 배지(# LL-0003, Lifeline Cell Technology, Frederick, MD)에서 <span class="math inline">\(80\%\)</span> 합생(confluency) 상태로 관리하였습니다. 인간 폐 섬유아세포(#CC-2512, Lonza)는 FibroLife 배지(#LL-0011, Lifeline Cell Technology)에서 배양하여 <span class="math inline">\(80\%\)</span> 합생 상태에 도달할 때까지 관리하였습니다. hFcRn-GFP/h <span class="math inline">\(\beta\)</span> m MDCK-II 및 모세포 MDCK-II 세포는 선행 연구에 기술된 방식대로 조달, 제작 및 배양하였습니다. 모든 부착 세포는 <span class="math inline">\(37^{\circ}\mathrm{C}\)</span>, <span class="math inline">\(5\%\)</span> <span class="math inline">\(\mathrm{CO}_{2}\)</span> 환경에서 배양되었습니다. 암젠 내부의 부유 배양용 CHO-K1 세포주는 <span class="math inline">\(50\%\)</span> EX-CELL 302 무혈청 배지(#14324C, Sigma-Aldrich, St.&nbsp;Louis, MO), <span class="math inline">\(50\%\)</span> 자체 제조 CHO-K1 성장 배지에 <span class="math inline">\(2\mathrm{mM}\)</span> L-글루타민(#25030081, Gibco/Thermo Fisher)을 첨가하여 사용하였으며, <span class="math inline">\(120\mathrm{rpm}\)</span>의 진탕기에서 주 2회 분할 배양하였습니다.</p>
</section>
<section id="단백질-설계" class="level2">
<h2 class="anchored" data-anchor-id="단백질-설계">단백질 설계</h2>
<p>설계된 모든 단백질의 백본(backbone) 설계에는 “Blueprint Builder” 방식이 적용되었습니다. 먼저 ABEGO 표기법을 통해 모든 아미노산의 phi/psi 빈(bins)을 지정한 뒤, 서열 정보 없이 Rosetta 폴딩 시뮬레이션을 수행하여 단백질 사슬의 phi/psi 빈을 제약하였습니다. PDB의 9개 아미노산 조각을 활용하여 목표한 빈과 일치하는 구조를 생성하고, 단순화된 에너지 함수를 바탕으로 몬테카를로(Monte Carlo) 방식으로 삽입하였습니다. 최종 단계에서는 3개 아미노산 조각으로 교체하여 백본 구조를 정밀하게 조정하였습니다.</p>
<p>FastDesign은 FastRelax 프로토콜 기반의 Rosetta 설계 프로세스입니다. 아미노산 서열을 반복적으로 설계하면서 원자 위치를 최소화하고, 반발력 가중치를 4단계(2%, 25%, 55%, 100%)에 걸쳐 점진적으로 증가시키며 Rosetta 에너지 함수를 최적화하였습니다(통상 3회 반복).</p>
<p>이후 포워드 폴딩(Forward folding)을 통해 설계된 서열의 폴딩 모델 환경을 샘플링하였습니다. 가장 낮은 에너지 구조가 설계된 구조 근처에 밀집되어 있고, 다른 영역에서 저에너지 대안이 발견되지 않을 때 성공적인 설계로 판단하였습니다.</p>
<p>스캐폴드별 상세 설계 방식은 다음과 같습니다. 5UOI의 경우 Blueprint Builder로 제작된 헬릭스 청크를 활용하고 FastDesign과 포워드 폴딩을 통해 서열을 최종 선정하였습니다.<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a> 2KL8 역시 Blueprint Builder로 백본을 생성한 후 FastDesign과 포워드 폴딩으로 서열을 확정하였습니다.<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a> TIM은 특정 시트(sheet) 및 헬릭스 길이를 지정하여 백본을 생성한 뒤, 루프에 수동 돌연변이를 도입하여 정제하였습니다.<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a> LCB1은 5UOI와 유사한 방식으로 백본을 만든 뒤 Patchdock/Rifdock 파이프라인으로 인터페이스를 정밀 설계하고 FastDesign으로 최적화하였습니다.<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a> TH1 단백질은 헬릭스 위치를 파라미터 방식으로 생성하고 PDB 조각 조회를 통해 루프를 연결한 뒤 FastDesign으로 서열을 확정하였습니다.<a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a></p>
</section>
<section id="플라스미드" class="level2">
<h2 class="anchored" data-anchor-id="플라스미드">플라스미드</h2>
<p>모든 데 노보 설계 단백질은 이펙터 기능이 제거된(effectorless) 인간 IgG1 Fc의 C-말단에 융합되었습니다.<a href="#fn7" class="footnote-ref" id="fnref7" role="doc-noteref"><sup>7</sup></a> DNA 조각은 IDT(Coralville, IA) 또는 Twist Bioscience(South San Francisco, CA)에서 합성하였으며, piggyBac(PB) 트랜스포세이즈 시스템 호환 벡터에 클로닝하여 서열을 확인하였습니다.<a href="#fn8" class="footnote-ref" id="fnref8" role="doc-noteref"><sup>8</sup></a> 모든 제작물은 형질전환(transfection) 전에 서열이 확인되었습니다.</p>
</section>
<section id="포유류-발현" class="level2">
<h2 class="anchored" data-anchor-id="포유류-발현">포유류 발현</h2>
<p>부유 배양용 CHO-K1 세포주는 EX-CELL 302 무혈청 배지(Sigma)와 <span class="math inline">\(2\mathrm{mM}\)</span> L-글루타민(Gibco)을 첨가한 맞춤형 CHO-K1 성장 배지에서 배양하였습니다. 모든 Fc 융합 단백질은 앞서 기술된 트랜스포즈 기반 기술을 통해 CHO-K1 세포에서 안정적으로 발현되었습니다.<a href="#fn9" class="footnote-ref" id="fnref9" role="doc-noteref"><sup>9</sup></a> 조건 배지(CM) 내 Fc 융합 단백질의 역가는 단백질 A 바이오센서(catalog no. 18-0004, ForteBio)를 이용한 옥텟(octet) 분석이나 SDS-PAGE로 추정하였습니다.</p>
</section>
<section id="재조합-단백질-정제" class="level2">
<h2 class="anchored" data-anchor-id="재조합-단백질-정제">재조합 단백질 정제</h2>
<p>단백질은 TBS(20 mM Tris, 150 mM NaCl, pH 7.5)로 미리 평형화된 mAb Select Sure 컬럼(catalog no. 11003495, Cytiva)에서 캡처되었습니다. TBS로 세척한 후, 결합된 단백질을 <span class="math inline">\(0.5\%\)</span> 아세트산, 150 mM NaCl, pH 3.5로 용리하였으며, HBS(30 mM HEPES, 150 mM NaCl, pH 7.6) 완충액을 사용하는 HiLoad Superdex 200 pg SEC 컬럼(cat. no. 28989336, Cytiva)을 통해 추가 정제하였습니다. 정제된 단백질은 <span class="math inline">\(0.22\mu \mathrm{m}\)</span> Posidyne 시린지 필터(cat. no. 4908, Pall Corporation)로 여과하여 <span class="math inline">\(-80^{\circ}\mathrm{C}\)</span> 에 보관되었습니다. 일부 단백질이 SEC에서 단일 피크를 보이지 않는 경우 2xPBS 완충액을 제형 완충액으로 사용하였습니다. 단백질 농도는 Nanodrop 분광 광도계(Thermo Fisher Scientific)로 측정하였습니다.</p>
</section>
<section id="분석용-sec" class="level2">
<h2 class="anchored" data-anchor-id="분석용-sec">분석용 SEC</h2>
<p>분석용 SEC는 HPLC(Agilent 1200 series)와 Sepax Zenix-C SEC-300 <span class="math inline">\(3\mu \mathrm{m}\)</span> <span class="math inline">\(300\times 4.6\)</span> mm LC 컬럼(cat no. 233300-4630, Sepax)을 사용하여 수행되었습니다. 분석 조건은 <span class="math inline">\(100~\mathrm{mM}\)</span> 인산나트륨 및 <span class="math inline">\(250~\mathrm{mMNaCl}\)</span>, pH 6.8에서 유속 <span class="math inline">\(0.45~\mathrm{mL / min}\)</span>, 실행 시간 <span class="math inline">\(12\mathrm{min}\)</span> 이었습니다.</p>
</section>
<section id="lc-ms를-이용한-온전한-질량-분석" class="level2">
<h2 class="anchored" data-anchor-id="lc-ms를-이용한-온전한-질량-분석">LC-MS를 이용한 온전한 질량 분석</h2>
<p>비환원 및 환원 LC-MS 분석용 샘플은 <span class="math inline">\(5\mu \mathrm{g}\)</span>의 단백질을 동일 부피의 <span class="math inline">\(0.1\%\)</span> 포름산과 혼합하여 준비했습니다. 환원 LC-MS 분석의 경우, <span class="math inline">\(5\mu \mathrm{g}\)</span>의 단백질을 <span class="math inline">\(8\mathrm{M}\)</span> 구아니딘 염산염과 혼합한 뒤 <span class="math inline">\(16.7~\mathrm{mM}\)</span> TCEP(cat no. 77720, Thermo Fisher Scientific)를 첨가하고 <span class="math inline">\(60^{\circ}\mathrm{C}\)</span>에서 <span class="math inline">\(30\mathrm{min}\)</span> 동안 반응시켰습니다. 샘플은 Agilent 6230 TOF 질량 분석기 및 Agilent 1200 HPLC 시스템을 통해 온전한 질량(intact mass)을 확인하였습니다. 분리는 C4 역상 컬럼(Mac-mod)을 사용하여 5-95% B 구배로 수행되었습니다.</p>
</section>
<section id="엔도톡신-측정" class="level2">
<h2 class="anchored" data-anchor-id="엔도톡신-측정">엔도톡신 측정</h2>
<p>모든 정제 단백질은 Endosafe LAL 카트리지와 nexgen-MCS(Charles River)를 사용하여 엔도톡신 수치가 <span class="math inline">\(0.5 \mathrm{EU/mg}\)</span> 미만임을 확인하였습니다.</p>
</section>
<section id="미세-모세관-전기영동mce" class="level2">
<h2 class="anchored" data-anchor-id="미세-모세관-전기영동mce">미세 모세관 전기영동(MCE)</h2>
<p>단백질 순도는 Caliper LabChip GXII 시스템(PerkinElmer)을 사용하여 특성화되었습니다. Protein express 시약 및 LabChip HT 칩을 사용하여 제조사 프로토콜에 따라 분석을 진행하였습니다. Chromeleon 소프트웨어(Thermo Fisher Scientific)를 사용하여 피크 면적을 적분하였습니다.</p>
</section>
<section id="단백질-특성의-인-실리코-계산" class="level2">
<h2 class="anchored" data-anchor-id="단백질-특성의-인-실리코-계산">단백질 특성의 인 실리코 계산</h2>
<p>모든 분자는 N-말단 Fc, Fc-단백질 링커, C-말단 His<span class="math inline">\(_6\)</span>-태그를 포함한 동일한 모듈을 가집니다. 데 노보 단백질 부분에 대해서만 속성 계산을 수행하였습니다. AlphaFold2를 이용해 3차원 구조를 예측한 뒤, MOE(Molecular Operating Environment)를 활용하여 나머지 계산을 수행하였습니다. LowModeMD를 통해 생리학적 pH 범위(6.4-8.4)에서 100개의 컨포머(conformer) 앙상블을 생성하고, 이에 대한 속성 평균값을 산출하였습니다.</p>
</section>
<section id="혈청-농도-약동학-연구" class="level2">
<h2 class="anchored" data-anchor-id="혈청-농도-약동학-연구">혈청 농도 약동학 연구</h2>
<p>모든 동물 실험은 AAALAC 가이드라인을 준수하며 Amgen 실험 동물 운영 위원회의 승인 하에 진행되었습니다. 암컷 야생형 C57BL/6J 마우스에 <span class="math inline">\(2\mathrm{mg/kg}\)</span>의 용량을 꼬리 정맥으로 정맥 주사하였습니다. 빈번한 채혈이 필요하여 단백질당 최소 2개 그룹의 마우스로 나누어 채혈 시점을 교차 배치하였습니다. 분리된 혈청은 <span class="math inline">\(-70^{\circ}\mathrm{C}\)</span> 에 보관하였으며, WatsonLIMS 소프트웨어를 통해 PK 매개변수를 산출하였습니다.</p>
</section>
<section id="생체-분포-연구" class="level2">
<h2 class="anchored" data-anchor-id="생체-분포-연구">생체 분포 연구</h2>
<p>생체 분포 연구를 위해 방혈 직후 주요 조직을 적출하여 <span class="math inline">\(0.9\%\)</span> 식염수로 세척한 뒤 급속 냉각하였습니다. 샘플링 시점은 내부 데이터와 선행 연구를 바탕으로 선정되었습니다.<a href="#fn10" class="footnote-ref" id="fnref10" role="doc-noteref"><sup>10</sup></a> 대식세포 고갈 실험에서는 단백질 투여 2일 전에 클로드로네이트(clodronate) 리포좀을 <span class="math inline">\(10\mu \mathrm{L}/ \mathrm{g}\)</span> 용량으로 투여하였습니다.<a href="#fn11" class="footnote-ref" id="fnref11" role="doc-noteref"><sup>11</sup></a></p>
</section>
<section id="마우스-혈청-및-조직-내-fc-융합-단백질-농도-정량" class="level2">
<h2 class="anchored" data-anchor-id="마우스-혈청-및-조직-내-fc-융합-단백질-농도-정량">마우스 혈청 및 조직 내 Fc 융합 단백질 농도 정량</h2>
<p>혈청 및 조직 내 농도는 MSD(Meso Scale Diagnostics) 장비를 이용한 전기 화학 발광 면역 분석법으로 정량화하였습니다. 비오틴화된 항-HIS 태그 항체를 캡처용으로, 루테닐화된 항-인간 Fc 항체를 검출용으로 사용하였습니다. 조직 샘플은 Precellys 균질기에서 용해 완충액과 함께 균질화하여 분석에 사용하였습니다.</p>
</section>
<section id="cho-k1-nse-측정" class="level2">
<h2 class="anchored" data-anchor-id="cho-k1-nse-측정">CHO-K1 NSE 측정</h2>
<p>CHO-K1 세포를 이용한 NSE 측정은 pH 5.8 또는 7.4 조건에서 유세포 분석법을 활용하여 선행 연구와 동일한 방식으로 수행하였습니다.[^44-45]</p>
</section>
<section id="fc-융합-단백질의-인간-fcrn-재활용-연구" class="level2">
<h2 class="anchored" data-anchor-id="fc-융합-단백질의-인간-fcrn-재활용-연구">Fc 융합 단백질의 인간 FcRn 재활용 연구</h2>
<p>인간 FcRn 재활용 실험은 hFcRn-GFP/h <span class="math inline">\(\beta\)</span> 2m MDCK II 세포를 사용하여 로드(load, 2시간) 및 재활용(recycle, 4시간) 단계별로 단백질 양을 MSD 분석으로 측정하였습니다. 섭취 단계는 <span class="math inline">\(37^{\circ}\mathrm{C}\)</span>에서 진행되었으며, 세포 용해물과 상층액을 각각 수집하여 분석하였습니다.<a href="#fn12" class="footnote-ref" id="fnref12" role="doc-noteref"><sup>12</sup></a></p>
</section>
<section id="mesoscale-discovery-면역-분석법에-의한-세포-hfcrn-재활용-분석-샘플-분석" class="level2">
<h2 class="anchored" data-anchor-id="mesoscale-discovery-면역-분석법에-의한-세포-hfcrn-재활용-분석-샘플-분석">MesoScale Discovery 면역 분석법에 의한 세포 hFcRn 재활용 분석 샘플 분석</h2>
<p>MSD 분석은 앞서 기술된 방식에서 항체 농도(1 <span class="math inline">\(\mu\mathrm{g}/ \mathrm{mL}\)</span>)와 완충액 조건을 최적화하여 수행되었습니다. 강력한 검출 신호를 확보하기 위해 MSD 리드 완충액 농도를 <span class="math inline">\(2\times\)</span>에서 <span class="math inline">\(1\times\)</span>로 낮추었습니다.</p>
</section>
<section id="인간-frem-점수" class="level2">
<h2 class="anchored" data-anchor-id="인간-frem-점수">인간 FREM 점수</h2>
<p>FREM(FcRn 재활용 효율 지표) 및 NUC(비특이적 섭취 계수) 점수를 산출하였습니다.[^45-46]<a href="#fn13" class="footnote-ref" id="fnref13" role="doc-noteref"><sup>13</sup></a> 모든 데이터는 SEFL2 수정 우스테키누맙으로 정규화되었습니다.</p>
</section>
<section id="단백질의-플루오레세인-이소티오시아네이트fitc-및-dylightdl-650-표지" class="level2">
<h2 class="anchored" data-anchor-id="단백질의-플루오레세인-이소티오시아네이트fitc-및-dylightdl-650-표지">단백질의 플루오레세인 이소티오시아네이트(FITC) 및 Dylight(DL) 650 표지</h2>
<p>TH1 전하 하위 시리즈를 NHS-FITC 또는 DyLight 650-NHS 에스테르로 표지하였습니다. 표지된 단백질은 Zeba 스핀 컬럼을 통해 정제되었으며, 최종 농도와 표지 효율은 Nanodrop으로 측정하였습니다.</p>
</section>
<section id="이미지화된-모세관-등전점-전기영동icief-분석" class="level2">
<h2 class="anchored" data-anchor-id="이미지화된-모세관-등전점-전기영동icief-분석">이미지화된 모세관 등전점 전기영동(icIEF) 분석</h2>
<p>CE-Infinite 시스템을 사용하여 등전점 변화를 정량화하였습니다. pI 마커를 사용하여 정확한 값을 측정하였으며, 데이터는 Agilent ChemStation 소프트웨어로 분석되었습니다.</p>
</section>
<section id="미세-유체-장치-내-미세-혈관-네트워크mvn-형성" class="level2">
<h2 class="anchored" data-anchor-id="미세-유체-장치-내-미세-혈관-네트워크mvn-형성">미세 유체 장치 내 미세 혈관 네트워크(MVN) 형성</h2>
<p>3D 미세 혈관 네트워크(MVN)는 HUVECs와 섬유아세포를 피브리노겐/트롬빈 젤 내에 공동 배양하여 형성하였습니다. 샘플은 7일 동안 매일 배지를 교체하며 유지되었습니다.</p>
</section>
<section id="mvn-내-정점-기저부-단백질-투과성-이미징" class="level2">
<h2 class="anchored" data-anchor-id="mvn-내-정점-기저부-단백질-투과성-이미징">MVN 내 정점-기저부 단백질 투과성 이미징</h2>
<p>공초점 현미경을 이용해 DL650 표지 단백질(<span class="math inline">\(0.6\mu \mathrm{M}\)</span>)과 TRITC-덱스트란(<span class="math inline">\(70\mathrm{kDa}, 0.6\mu \mathrm{M}\)</span>)의 투과성을 시각화하였습니다. <span class="math inline">\(37^{\circ}\mathrm{C}\)</span> 환경에서 0분과 <span class="math inline">\(12\mathrm{~min}\)</span>에 이미지를 획득하여 형광 강도 변화를 정량화하였습니다.<a href="#fn14" class="footnote-ref" id="fnref14" role="doc-noteref"><sup>14</sup></a></p>
</section>
<section id="mvn-내-단백질-투과성-이미지-분석" class="level2">
<h2 class="anchored" data-anchor-id="mvn-내-단백질-투과성-이미지-분석">MVN 내 단백질 투과성 이미지 분석</h2>
<p>맞춤형 Python 워크플로와 Ilastik 분할 도구를 사용하여 투과 계수(<span class="math inline">\(\mathrm {c m / s e c}\)</span>)를 계산하였습니다.[^62-64] Random Forest 분류기를 통해 매트릭스와 혈관 영역을 분리하고, 부피 및 표면적 데이터를 추출하였습니다.</p>
<p><span class="math display">\[
\text {투과성} (\mathrm {c m / s e c}) = \frac {1}{\Delta t} \frac {V _ {\mathrm { M }}}{S A _ {\mathrm { V }}} \frac {\Delta I _ {\mathrm { M }}}{\Delta I}
\]</span></p>
<p>여기서 <span class="math inline">\(\Delta t\)</span>는 시작 및 최종 이미지 획득 사이의 시간 차이이고, <span class="math inline">\(V_{\mathrm{M}}\)</span>은 매트릭스 부피, <span class="math inline">\(SA_{\mathrm{V}}\)</span>는 혈관의 표면적, <span class="math inline">\(\Delta I_{\mathrm{M}}\)</span>은 세포외 매트릭스 내 강도의 증가를 나타내며, <span class="math inline">\(\Delta I = I_{V(t = 0)} - I_{\mathrm{M}(t = 0)}\)</span>은 실험 시작 시 혈관과 매트릭스 사이의 평균 강도 차이를 보고합니다.</p>
</section>
<section id="미세-유체-장치-내-인-비트로-간질-상호작용-측정" class="level2">
<h2 class="anchored" data-anchor-id="미세-유체-장치-내-인-비트로-간질-상호작용-측정">미세 유체 장치 내 인 비트로 간질 상호작용 측정</h2>
<p>FRAP법을 사용하여 단백질의 확산 계수 및 비이동 분율을 측정했습니다.<a href="#fn15" class="footnote-ref" id="fnref15" role="doc-noteref"><sup>15</sup></a><a href="#fn16" class="footnote-ref" id="fnref16" role="doc-noteref"><sup>16</sup></a> <span class="math inline">\(0.6\mu \mathrm{M}\)</span> FITC 표지 단백질을 장치 측면 채널에 첨가하고 <span class="math inline">\(24\mathrm{h}\)</span> 동안 배양했습니다. 다음 날, SP8 공초점 현미경에서 FRAP 분석을 수행하여 단백질의 확산 속도를 산출했습니다. 비이동 분율은 발표된 방법에 따라 계산되었습니다.[^66-67]</p>
<p><img src="images/66751168f78251becf7f9744f39d449f5736b25d35bec92d0e9a0524c9bc8aed.jpg" class="img-fluid"></p>
<p>그림 1. 목표 물리화학적 특성을 가진 설계된 데 노보 Fc 융합 단백질 패널. 등전점(pI), 표면 패치 및 크기를 포함하여 광범위한 생물물리학적 특성을 포괄하도록 35개의 데 노보 단백질 패널이 설계되었습니다. (A) 대표적인 Fc 융합 단백질의 AlphaFold2 구조(왼쪽). 융합 패널에는 서로 다른 데 노보 스캐폴드가 포함되었습니다(오른쪽). 생물물리학적 계산은 Fc와 링커 없이 데 노보 단백질에 대해서만 수행되었습니다. 알파 헬릭스와 베타 시트는 각각 녹색과 파란색으로 표시됩니다. (B) 각 데 노보 스캐폴드에 대한 서로 다른 전하 변이체의 대표 구조. 표면 패치는 범례에 표시된 색상으로 표시됩니다. 표면 패치로 인정되려면 <span class="math inline">\(40\AA^2\)</span> 이상의 연속된 전하 표면적 또는 <span class="math inline">\(50\AA^2\)</span> 이상의 연속된 소수성 표면적이 필요했습니다. 더 나은 시각화를 위해 앞면의 패치는 숨겨져 있습니다.</p>
<p>그림 2. 설계된 데 노보 단백질 패널. 35개 데 노보 단백질 모두 이름과 pI 값이 표시되어 있습니다. 양성(파란색), 음성(빨간색) 및 소수성(녹색) 패치가 표시됩니다. 각 변이체는 왼쪽에서 오른쪽으로 pI가 증가하는 순서(낮은 pI; 산성, 높은 pI; 염기성)로 배열되며 알파벳순으로 고유 식별 문자가 부여됩니다. 결과적으로 각 스캐폴드 내에서 가장 산성인 변이체는 A로 라벨링되었으며 가장 염기성인 pI 값까지 이어집니다(예: 2KL8-A는 pI가 가장 산성인 2KL8 스캐폴드의 단백질 변이체이고 2KL8-E는 가장 염기성임). LCB1 및 TH1 전하 시리즈의 경우, 각 시리즈에서 선택된 3개의 대표 변이체에 서로에 대한 상대적 pI 값에 해당하는 명칭을 부여했습니다(예: 산성, 중성 근처, 염기성. 여기서 산성-TH1은 선택된 3개 TH1 단백질 중 pI가 가장 낮음).</p>
<p>표 1. 모든 Fc 융합 단백질의 약동학적 특성 및 제거율과 유의미하게 상관관계가 있는 3가지 기술자 값</p>
<table>
<tbody><tr>
<td>
융합 단백질
</td>
<td>
MW (kDa)
</td>
<td>
AUC0-last (nM × hr)
</td>
<td>
제거율 (mL/h/kg)
</td>
<td>
pI_seq
</td>
<td>
알짜 전하
</td>
<td>
patch_pos_%
</td>
</tr>
<tr>
<td>
2KL8-A
</td>
<td>
7.20 × 10^1
</td>
<td>
2.59 × 10^3
</td>
<td>
1.08 × 10^1
</td>
<td>
3.64 × 10^0
</td>
<td>
-1.59 × 10^1
</td>
<td>
1.46 × 10^0
</td>
</tr>
<tr>
<td>
2KL8-B
</td>
<td>
7.20 × 10^1
</td>
<td>
4.69 × 10^3
</td>
<td>
5.92 × 10^0
</td>
<td>
3.93 × 10^0
</td>
<td>
-1.13 × 10^1
</td>
<td>
3.29 × 10^0
</td>
</tr>
<tr>
<td>
2KL8-C
</td>
<td>
7.24 × 10^1
</td>
<td>
4.24 × 10^3
</td>
<td>
6.51 × 10^0
</td>
<td>
4.70 × 10^0
</td>
<td>
-2.98 × 10^0
</td>
<td>
1.07 × 10^1
</td>
</tr>
<tr>
<td>
2KL8-D
</td>
<td>
7.20 × 10^1
</td>
<td>
4.36 × 10^3
</td>
<td>
6.37 × 10^0
</td>
<td>
7.18 × 10^0
</td>
<td>
-2.06 × 10^-1
</td>
<td>
7.77 × 10^0
</td>
</tr>
<tr>
<td>
2KL8-E
</td>
<td>
7.22 × 10^1
</td>
<td>
1.28 × 10^3
</td>
<td>
2.17 × 10^1
</td>
<td>
1.01 × 10^1
</td>
<td>
3.54 × 10^0
</td>
<td>
1.27 × 10^1
</td>
</tr>
<tr>
<td>
SUOI-A
</td>
<td>
6.34 × 10^1
</td>
<td>
1.54 × 10^4
</td>
<td>
2.05 × 10^0
</td>
<td>
3.84 × 10^0
</td>
<td>
-1.10 × 10^1
</td>
<td>
1.84 × 10^0
</td>
</tr>
<tr>
<td>
SUOI-B
</td>
<td>
6.35 × 10^1
</td>
<td>
2.06 × 10^4
</td>
<td>
1.53 × 10^0
</td>
<td>
4.22 × 10^0
</td>
<td>
-6.48 × 10^0
</td>
<td>
3.83 × 10^0
</td>
</tr>
<tr>
<td>
SUOI-C
</td>
<td>
6.33 × 10^1
</td>
<td>
1.08 × 10^4
</td>
<td>
2.92 × 10^0
</td>
<td>
4.31 × 10^0
</td>
<td>
-4.06 × 10^0
</td>
<td>
5.26 × 10^0
</td>
</tr>
<tr>
<td>
SUOI-D
</td>
<td>
6.34 × 10^1
</td>
<td>
3.46 × 10^3
</td>
<td>
9.13 × 10^0
</td>
<td>
6.38 × 10^0
</td>
<td>
-2.19 × 10^-2
</td>
<td>
8.57 × 10^0
</td>
</tr>
<tr>
<td>
SUOI-E
</td>
<td>
6.35 × 10^1
</td>
<td>
9.18 × 10^3
</td>
<td>
3.43 × 10^0
</td>
<td>
6.44 × 10^0
</td>
<td>
-2.71 × 10^-2
</td>
<td>
1.09 × 10^1
</td>
</tr>
<tr>
<td>
SUOI-F
</td>
<td>
6.35 × 10^1
</td>
<td>
1.84 × 10^3
</td>
<td>
1.71 × 10^1
</td>
<td>
9.89 × 10^0
</td>
<td>
1.04 × 10^0
</td>
<td>
1.42 × 10^1
</td>
</tr>
<tr>
<td>
SUOI-G
</td>
<td>
6.35 × 10^1
</td>
<td>
4.25 × 10^3
</td>
<td>
7.41 × 10^0
</td>
<td>
9.89 × 10^0
</td>
<td>
1.03 × 10^0
</td>
<td>
1.42 × 10^1
</td>
</tr>
<tr>
<td>
SUOI-H
</td>
<td>
6.34 × 10^1
</td>
<td>
2.03 × 10^3
</td>
<td>
1.55 × 10^1
</td>
<td>
1.05 × 10^1
</td>
<td>
2.10 × 10^1
</td>
<td>
1.43 × 10^1
</td>
</tr>
</tbody></table>
</section>
</section>
<section id="결과" class="level1">
<h1>결과</h1>
<section id="다양한-물리화학적-속성을-가진-fc-융합-단백질-패널의-설계-및-생산" class="level2">
<h2 class="anchored" data-anchor-id="다양한-물리화학적-속성을-가진-fc-융합-단백질-패널의-설계-및-생산">다양한 물리화학적 속성을 가진 Fc 융합 단백질 패널의 설계 및 생산</h2>
<p>우리는 Fc 융합체 소실에 미치는 생물물리학적 특성의 영향을 체계적으로 연구하기 위해 데 노보 생성 단백질을 모델로 선정하였습니다. 인 실리코에서 설계된 이러한 이상적인 스캐폴드는 크기와 토폴로지가 다르며, 이론적으로 구조적 안정성을 유지하면서 표면 아미노산 조성을 극적으로 변화시킬 수 있습니다. 총 5종의 독창적인 스캐폴드가 선택되었습니다: 3개의 <span class="math inline">\(\alpha\)</span>-헬릭스를 가진 <span class="math inline">\(4.8\mathrm{kDa}\)</span> 최소 단백질(PDB ID: 5UOI; <a href="#fn17" class="footnote-ref" id="fnref17" role="doc-noteref"><sup>17</sup></a>), SARS-CoV-2 스파이크 단백질에 결합하는 LCB1로 명명된 <span class="math inline">\(6.7\mathrm{kDa}\)</span> 미니 바인더(PDB ID: 7JZL 및 7JZU; <a href="#fn18" class="footnote-ref" id="fnref18" role="doc-noteref"><sup>18</sup></a>), <span class="math inline">\(9\mathrm{kDa}\)</span> 페레독신 유사 폴드 단백질(PDB ID: 2KL8; <a href="#fn19" class="footnote-ref" id="fnref19" role="doc-noteref"><sup>19</sup></a>), <span class="math inline">\(18\mathrm{kDa}\)</span> 4-헬릭스 번들 단백질 TH1, 그리고 <span class="math inline">\(20\mathrm{kDa}\)</span> TIM 배럴(PDB ID: 5BVL, 6WVS; <a href="#fn20" class="footnote-ref" id="fnref20" role="doc-noteref"><sup>20</sup></a>[^68-69]). 각 스캐폴드에 대해 높은, 중성, 낮은 pI를 가지며 표면의 양성, 음성 또는 소수성 패치의 크기와 분포가 서로 다른 변이체들이 설계되었습니다. 이를 위해 MPNN을 사용하여 허용 가능한 아미노산 돌연변이를 찾고, 목표하는 표면 분포를 달성하는 데 필요한 최소한의 점 돌연변이를 수동으로 선택한 뒤, 마지막으로 AlphaFold2를 사용하여 돌연변이된 단백질이 여전히 동일한 형태로 접히는지 확인하였습니다.[^70-71]</p>
<p>이를 통해 크기가 5 ~ <span class="math inline">\(20\mathrm{kDa}\)</span>이며, pI가 약 4, 7 또는 9이고 표면 전하 및 소수성 수준이 다른 단백질 패널이 성공적으로 생성되었습니다(그림 1 및 2, 표 1). 이러한 단백질들은 인간 IgG1 SEFL2 Fc의 C-말단에 융합되어 포유류 세포에서 발현 및 분비되었으며 정제되었습니다.<a href="#fn21" class="footnote-ref" id="fnref21" role="doc-noteref"><sup>21</sup></a><a href="#fn22" class="footnote-ref" id="fnref22" role="doc-noteref"><sup>22</sup></a> pI가 9보다 큰 Fc 융합 단백질은 일반적으로 생산하기 더 어려웠으며, 종종 고양전하 함량으로 인해 단백질 분해 절단(proteolytic cleavage)이 발생하기 쉬웠습니다(데이터 미표시). 절단된 제품이 <span class="math inline">\(30\%\)</span>를 초과하는 로트는 폐기되었습니다. 최종 패널은 인 비보 PK 분석을 위한 35개의 고유한 Fc 융합 단백질로 구성되었습니다(표 S1).</p>
</section>
<section id="인-실리코-전하-기술자는-야생형-마우스에서의-제거율과-가장-강력하게-상관관계를-나타낸다" class="level2">
<h2 class="anchored" data-anchor-id="인-실리코-전하-기술자는-야생형-마우스에서의-제거율과-가장-강력하게-상관관계를-나타낸다">인 실리코 전하 기술자는 야생형 마우스에서의 제거율과 가장 강력하게 상관관계를 나타낸다</h2>
<p>그림 3. 전하 기술자는 마우스 제거율과 가장 강력하게 상관관계를 나타낸다.</p>
<p><img src="images/bf193ce4738b71c3813f939aef9407ee320c07535bb281739942de2da857b463.jpg" class="img-fluid"></p>
<p><img src="images/0f933ab8f00f5cc5aba547e5ffcc3e9e073ea79c6f7174d6ab388ba523d50d13.jpg" class="img-fluid"></p>
<p><img src="images/f70c3bc4624c22cd8dc12b7deed0163eb3211fdf1b1b2f1904b8864c1bf49e39.jpg" class="img-fluid"></p>
<p><img src="images/a477fa0a56076b0208fedde9955046e92e080b7ddf46bbe17be88da5a8560029.jpg" class="img-fluid"></p>
<p><img src="images/cd3c3c5ae7220b6a9504f367dddb31707d0ab60b061e95bc06e0990c86c05e66.jpg" class="img-fluid"></p>
<p><img src="images/e80a81cf159839aa98771588d4f484e1991202443f4b1f84e672a47c7312f5da.jpg" class="img-fluid"></p>
<ol type="A">
<li>스캐폴드별로 그룹화된 C57BL/6J 마우스에 단일 정맥 볼루스 용량<span class="math inline">\((2\mathrm{mg / kg})\)</span>을 투여한 후 각 Fc 융합 단백질의 혈청 농도-시간 프로필.</li>
</ol>
<p><img src="images/0a0aa85dd187f7367599e3ebacfe110e54555562fd21ccfdb322c18ca696626a.jpg" class="img-fluid"></p>
<ol start="2" type="A">
<li>비구획 분석을 사용하여 제거율(CL) 추정치를 얻었으며, <span class="math inline">\(1.53\times 10^{0}\)</span> 에서 <span class="math inline">\(1.27\times 10^{3}\mathrm{mL/h/kg}\)</span>까지 넓은 범위의 값이 관찰되었습니다.</li>
</ol>
<p><img src="images/f9bbd4109eda9e4e11f5e0b1f2b9fc04abf4cc7c642fcde270ee90a0b5a2f48c.jpg" class="img-fluid"></p>
<p><img src="images/a20a543956d389f6f80e015eff506c8c7c950001a97d8af08ed128e5b81b50d1.jpg" class="img-fluid"></p>
<p><img src="images/7a135f0686c7da1e48df81dc9d32eb8df952a883b00b1f14631bc55a186013ce.jpg" class="img-fluid"></p>
<ol start="3" type="A">
<li>설계된 각 Fc 융합 단백질에 대해 데 노보 부분의 아미노산 서열만을 사용하여 물리화학적 기술자를 계산했습니다. CL과 가장 강력하게 연관된 서열 기반 기술자를 식별하기 위해 스피어만(Spearman) 상관관계 매트릭스를 수행했습니다. 평가된 53개 파라미터 중 서열 기반 pI(pI_seq), 알짜 전하 및 양성 단백질 패치의 총 표면적 백분율(patch_pos %)이 가장 높은 스피어만 상관관계를 나타냈습니다.</li>
</ol>
<p><img src="images/64ff0fc319d1cef4326668e52764b0d669853fb7ad11a5cb1942e4ced6ca6c29.jpg" class="img-fluid"></p>
<ol start="4" type="A">
<li>개별 Fc 융합 스캐폴드 조사 결과, 양의 알짜 전하가 증가함에 따라 CL이 감소하다가 다시 증가하는 U자형 관계가 입증되었습니다.</li>
</ol>
<p><img src="images/3d07700314703c37518a28747ceeefbfc507792ef15c5b5db2e3ae04fb537602.jpg" class="img-fluid"></p>
<ol start="5" type="A">
<li>모든 단백질 CL 값을 알짜 전하에 따라 빈으로 나누어 동시에 그래프로 나타냈습니다. 알짜 음전하 또는 양전하의 극단이 중간 그룹에 비해 CL이 유의하게 높은 명확한 U자형 관계가 관찰되었습니다. Kruskal-Wallis 테스트, <span class="math inline">\(^*p&lt;0.05\)</span>, <span class="math inline">\(^{**}p&lt;0.01\)</span>.</li>
</ol>
<p>모든 Fc 융합 단백질은 야생형 C57BL/6J 마우스에 <span class="math inline">\(2\mathrm{mg / kg}\)</span> 정맥 볼루스 용량으로 개별 투여되었습니다. 야생형 마우스에는 알려진 결합 파트너가 존재하지 않을 것으로 예상되었으므로, 각 단백질의 비구획 분석을 통해 얻은 총 제거율(CL)은 표적 독립적 매개 과정에 의해 주도되는 <span class="math inline">\(\mathrm{CL}_{\mathrm{ind}}\)</span> 또는 CL로 해석되었습니다. 혈청 농도-시간 프로필에서 상당한 차이가 있었으며, <span class="math inline">\(1.53 \times 10^{0}\)</span> 에서 <span class="math inline">\(1.27 \times 10^{3} \mathrm{~mL / h / kg}\)</span>에 이르는 넓은 CL 범위가 관찰되었습니다(그림 3A,B 및 표 1). 분자량과 CL 또는 곡선 아래 면적(AUC)으로 결정된 총 혈청 노출 사이에는 아무런 관계가 확인되지 않았습니다(그림 S1A).</p>
<p>마우스 CL과 가장 연관성이 높은 물리화학적 속성을 식별하기 위해 스피어만 상관관계 매트릭스를 시작점으로 수행했습니다(그림 3C). 이러한 기술자들은 Alpha-Fold 예측 입력 구조에 대해 LowModeMD를 실행하여 생성된 데 노보 모듈의 형태 앙상블을 사용하여 MOE에서 계산되었습니다. 앙상블 계산은 설계된 단백질 부분(예: <span class="math inline">\(\sim 64\mathrm{kDa}\)</span>의 이가 Fc 융합체가 아닌 <span class="math inline">\(7\mathrm{kDa}\)</span> LCB1)만을 사용하여 얻었습니다.</p>
<p>아미노산 서열로부터 계산된 등전점(pI_seq, 스피어만 <span class="math inline">\(r = 0.44\)</span>, <span class="math inline">\(p &lt; 0.01\)</span>), 아미노산 서열로부터 계산된 알짜 전하(스피어만 <span class="math inline">\(r = 0.47\)</span>, <span class="math inline">\(p &lt; 0.01\)</span>), 그리고 양성 단백질 패치 표면적 백분율(patch_pos_%, 스피어만 <span class="math inline">\(r = 0.47\)</span>, <span class="math inline">\(p &lt; 0.01\)</span>)이 CL과 가장 높은 스피어만 상관관계를 가진 인 실리코 기술자로 식별되었습니다(그림 3C, 표 S2-S4). 상위 3개 상관 파라미터와 CL의 개별 플롯을 조사한 결과, 파라미터 값이 증가함에 따라 CL이 감소하다가 다시 증가하는 스캐폴드 시리즈 내의 U자형 관계가 밝혀졌습니다(그림 3D, S1B,C). 이러한 경향은 알짜 전하에서 가장 뚜렷했으며, 모든 데 노보 스캐폴드 시리즈에서 고리 모양의 꼬리(hooked tail)가 관찰되었습니다. 이 효과는 5UOI 및 TIM 시리즈에서 약간 덜 두드러졌는데, 이는 아마도 강한 음전하(알짜 전하 -15 이하)를 가진 변이체가 부족했기 때문일 것입니다. 이는 모든 단백질에 대해 계산된 CL 값을 알짜 전하를 기준으로 5개 빈에 넣어 그래픽으로 묘사되었으며, 중간값에 비해 반대 극성의 극단에서 CL이 유의하게 상승하는 것이 관찰되었습니다(그림 3E).</p>
<p>그림 4. 상대적으로 과도한 음전하 또는 양전하를 가진 단백질은 조직 축적이 증가한다. (A) 알짜 전하와 (B) 제거율(CL) 사이의 U자형 관계를 나타낸 TH1 및 LCB1 모달리티의 총 6개 단백질(산성, 염기성 및 중성 근처 pI). (C) 중성 근처 pI 단백질에 비해 모든 전하 변이체의 노출 감소 및 CL 증가를 보여주는 혈청 농도 시간 프로필. 점당 <span class="math inline">\(N = 3\)</span> 마리의 별개 동물. (D) C57BL/6J 마우스에 정맥 볼루스 용량<span class="math inline">\((2\mathrm{mg / kg})\)</span>을 투여한 후 30분 후 간, 신장 및 비장 내 조직 농도를 조사하여 생체 분포 연구를 수행했습니다. 중성 근처 pI 비교군에 비해 알짜 전하 극단을 가진 모든 단백질에서 조직 정체가 유의하게 증가하는 것이 관찰되었습니다. 각 점은 개별 동물을 나타내며, Dunnett의 다중 비교를 포함한 이원 ANOVA; ns, 유의하지 않음, <span class="math inline">\(^{*}p &lt; 0.05\)</span>, <span class="math inline">\(^{**}p &lt; 0.01\)</span>, <span class="math inline">\(^{****}p &lt; 0.0001\)</span>.</p>
<ol type="A">
<li><p><img src="images/a6cf79f7435b5b58e4defd267649638be9eace7f5d9de3493fd5f449acba6cd3.jpg" class="img-fluid"></p></li>
<li><p><img src="images/18f73c2d079fccb4f2a60383ebb43a6d0eb9c0185c548b9187ba7523dacbaa45.jpg" class="img-fluid"></p></li>
<li><p><img src="images/ac0941aeef313d79ca074fb1c5f413869e4ba96144023de2e002484c8f1340de.jpg" class="img-fluid"></p></li>
<li><p><img src="images/da0542a0d06c3d441404332fdb61a7c265c5c0299e97ad73150933fa3e9a8609.jpg" class="img-fluid"><br>
<img src="images/f09b7b761e0bf4b0e32280dedacd8566a254e775ca90f8c43a391eaec4c0e1ba.jpg" class="img-fluid"></p></li>
</ol>
</section>
<section id="상대적인-알짜-전하-극단은-cl-증가-및-조직-축적-상승과-연관되어-있다" class="level2">
<h2 class="anchored" data-anchor-id="상대적인-알짜-전하-극단은-cl-증가-및-조직-축적-상승과-연관되어-있다">상대적인 알짜 전하 극단은 CL 증가 및 조직 축적 상승과 연관되어 있다</h2>
<p>우리는 TH1 및 LCB1 단백질의 하위 세트에서 마우스 생체 분포 평가를 수행하여 알짜 전하에 대한 관찰을 확장했습니다. 이러한 스캐폴드들은 넓은 범위의 CL을 가진 단백질들과 상대적 pI 값을 기반으로 명명된 여러 돌연변이체를 포함하고 있었기 때문입니다. 이에 따라 5개의 TH1 단백질에는 산성-TH1, 중성 근처-TH1, 염기성-TH1 및 두 개의 추가 중성 근처 변이체(TH1-A 및 TH1-B)가 포함되었습니다. 11개의 LCB1 단백질은 산성-LCB1, 중성 근처-LCB1, 염기성-LCB1 및 8개의 추가 변이체: 산성 2개(LCB1-A, LCB1-B), 중성 근처 2개(LCB1-C, LCB1-D), 염기성 4개(LCB1-F, LCB1-E, LCB1-G, LCB1-H)였습니다. LCB1-G는 일부 Asp, Glu, Arg, Lys 잔기를 Gln으로 교체하여 전하 잔기 수를 줄였으며, LCB1-H는 거의 모든 Asp, Glu, Arg, Lys 잔기를 Gln으로 교체하여 가장 적은 전하 잔기를 가졌습니다.</p>
<p>이로부터 중성 근처 pI 단백질 1개(near-neutral-TH1 및 near-neutral-LCB1), 더 음의 알짜 전하를 가진 산성 단백질 1개(acidic-TH1 및 acidic-LCB1), 더 양의 알짜 전하를 가진 염기성 단백질 1개(basic-TH1 및 basic-LCB1)를 선택했습니다(그림 4A-C, 표 1). 마우스 간, 신장 및 비장을 단백질당 <span class="math inline">\(2\mathrm{mg/kg}\)</span> 용량으로 정맥 볼루스 투여 후 30분에 수집했습니다. 이 조직들은 높은 혈류 속도와 항체 이화작용에 대한 기여도, 그리고 단백질 전하가 생체 분포에 미치는 영향을 입증한 선행 연구를 바탕으로 선택되었습니다.<a href="#fn23" class="footnote-ref" id="fnref23" role="doc-noteref"><sup>23</sup></a><a href="#fn24" class="footnote-ref" id="fnref24" role="doc-noteref"><sup>24</sup></a>[^73-79] 그 결과, 빈(bin)에 관계없이 동일한 스캐폴드의 중성 근처 pI 단백질에 비해 과도한 알짜 전하를 가진 변이체에서 조직/혈청 비율이 증가하는 것을 관찰했습니다(그림 4D). 이는 모체 형태와 알짜 전하 차이가 큰 단백질이 더 빠른 CL과 더 높은 조직 축적을 나타낸다는 다른 연구자들의 연구 결과와 일치합니다.[^36-38][^41-42]<a href="#fn25" class="footnote-ref" id="fnref25" role="doc-noteref"><sup>25</sup></a><a href="#fn26" class="footnote-ref" id="fnref26" role="doc-noteref"><sup>26</sup></a></p>
</section>
<section id="fc-융합체의-cl을-결정하는-세포-과정에서-전하의-역할" class="level2">
<h2 class="anchored" data-anchor-id="fc-융합체의-cl을-결정하는-세포-과정에서-전하의-역할">Fc 융합체의 CL을 결정하는 세포 과정에서 전하의 역할</h2>
<p>우리의 다음 목표는 전하에 민감한 단백질 소실을 주도하는 지배적인 기전을 확립하는 것이었으며, 초기에는 항체와 Fc 융합 단백질이 공유하는 혈청 PK, 즉 공통 <span class="math inline">\(\mathrm{CL}_{\mathrm{ind}}\)</span> 경로에 집중했습니다. 항체에 중요한 정전기적 제거 기전이 새로운 Fc 융합 단백질에도 적용되어, 높은 용매 노출 양전하가 NSE를 향상시키고 세포 내 비특이적 결합을 높이며 FcRn 재활용 효율을 감소시킬 것이라고 가설을 세웠습니다.<a href="#fn27" class="footnote-ref" id="fnref27" role="doc-noteref"><sup>27</sup></a> 이는 pH 5.8 및 7.4 조건에서 CHO-K1 세포 내의 비특이적 단백질 내부화를 정량화하는 기 구축된 세포 기반 분석법을 통해 테스트되었습니다.[^44-45] 중성 근처 pH에서의 분석은 세포외 환경과 유사한 조건 하에서의 NSE를 직접 평가하는 것이며, 산성 pH 5.8 조건은 엔도좀 트래피킹 중의 산성화로 인해 비특이적 변화가 일어날 수 있고 FcRn 상호작용이 발생하는 엔도좀 환경을 모사하기 위함입니다.</p>
<p>전체 Fc 융합 단백질 시리즈에 걸쳐 넓은 범위의 NSE 값이 측정되었으며, 이는 테스트된 두 pH 값 모두에서 마우스 CL과 유세포 분석법에서 유의미한 상관관계를 나타냈습니다(pH 5.8에서 스피어만 <span class="math inline">\(r = 0.55, p &lt; 0.001\)</span>; pH 7.4에서 <span class="math inline">\(0.54, p &lt; 0.001\)</span>; 그림 S2A-C). 조사된 거의 모든 단백질에서 pH 7.4 대비 pH 5.8에서 NSE가 증가하는 것이 관찰되었으며(그림 S2A, B), 이는 산성 pH에서의 세포 비특이적 상호작용 증가를 시사합니다.<a href="#fn28" class="footnote-ref" id="fnref28" role="doc-noteref"><sup>28</sup></a> NSE와 pH 의존적 관계에 대한 관찰을 강화하기 위해, 본 연구를 위해 pH 5.8에서 추가 측정한 8종을 포함하여 이전 보고서의 18종 항체에 대한 평가 결과를 포함시켰습니다.[^44-45] 모든 항체는 산성 pH에서 NSE 증가를 보였으며(그림 S2D), 54종 전체 단백질(항체 18종, Fc 융합체 35종)에 대해 플롯한 두 pH에서의 NSE 값은 강력한 상관관계를 나타냈습니다(그림 S2E). 이러한 관찰은 산성 pH에서의 높은 양전하가 치료용 단백질의 세포 비특이성을 향상시킬 수 있다는 우리의 이전 결론을 뒷받침하며, 초기 관찰을 확장하여 Fc-단백질 모달리티와 무관한 보다 일반적인 기전임을 시사합니다.<a href="#fn29" class="footnote-ref" id="fnref29" role="doc-noteref"><sup>29</sup></a></p>
<p>물리화학적 특성이 Fc 융합 단백질 <span class="math inline">\(\mathrm{CL}_{\mathrm{ind}}\)</span>에 중요한 세포 과정에 어떻게 정보를 제공할 수 있는지 더 잘 이해하기 위해, pH 7.4에서의 CHO-K1 NSE 값과 알짜 전하, pI_seq 또는 patch_pos_% 사이의 관계를 그래픽으로 탐색했습니다. 함께 분석했을 때, 모든 지표는 주어진 기술자의 정체기(plateau)를 포함하는 광범위한 NSE 범위를 가진 S자형 관계를 보여주었습니다(그림 5C). 또한 NSE와 소수성 기술자 사이에는 아무런 연관성이 발견되지 않았습니다(그림 S3). 마찬가지로 NSE 측정값을 알짜 전하에 따라 빈으로 나누었을 때도 유사한 결과가 나타났습니다. 알짜 전하가 양의 방향으로 갈수록 일반적인 증가가 관찰되었으나, 전하가 유사한 단백질들 사이에서도 엄청난 변동이 확인되었습니다(그림 5D). 이러한 관찰과 일치하게, 항체의 서열 기반 알짜 전하를 전체 아미노산 서열을 사용한 Fc 융합체의 계산된 알짜 전하와 함께 포함시켰을 때도 pH 7.4에서의 NSE와 아무런 관계를 보이지 않았습니다(그림 S4A).<a href="#fn30" class="footnote-ref" id="fnref30" role="doc-noteref"><sup>30</sup></a> 그러나 개별 Fc 단백질 스캐폴드를 조사했을 때는 NSE 증가가 일반적으로 양전하 증가와 연관되어 유의미한 상관관계가 입증되었습니다(그림 5E, S4B,C).</p>
<p>다음으로, 인간 <span class="math inline">\(\beta 2\mathrm{m}\)</span> 및 GFP 표지된 인간 FcRn이 안정적으로 공동 형질전환된 MDCK II 세포(hFcRn-GFP/h <span class="math inline">\(\beta 2\mathrm{m}\)</span>-MDCK II 세포)를 사용하여 기 개발된 방법으로 Fc 융합 단백질의 전하 특성이 FcRn 재활용 효율에 미치는 영향을 직접 측정했습니다(그림 S5A). 이 분석은 모세포 MDCK II와 hFcRn-GFP/h <span class="math inline">\(\beta 2\mathrm{m}\)</span>-MDCK II 세포를 모두 포함하며, pH 5.8에서 테스트 단백질과 함께 배양합니다. 분석 감도를 높여 NSE가 낮은 Fc 함유 단백질을 과도한 시료 소모 없이 평가하기 위해 산성 pH 조건을 선택했습니다. 분석의 “로드(load)” 단계 후 세포를 세척하고 용해하거나(섭취 분율), 무혈청 배지에서 배양하여 FcRn 매개 재활용을 유도합니다. 이후 배지를 수집하고(재활용 분율), 남은 세포를 용해하여(잔류 분율) 항-인간 Fc 면역 분석법으로 정량합니다. hFcRn 재활용 효율 지표(FREM)는 두 세포주에서의 결과를 통합하여 산출합니다(상세 내용은 방법 참조). 이전 보고서에서 참조 화합물 대비 <span class="math inline">\(50\%\)</span> 미만의 FREM 점수를 가진 항체는 <span class="math inline">\(\mathrm{CL}_{\mathrm{ind}}\)</span> 상승 위험이 높은 것으로, <span class="math inline">\(25\%\)</span> 미만은 신속한 <span class="math inline">\(\mathrm{CL}_{\mathrm{ind}}\)</span>를 갖는 것으로 식별되었습니다.<a href="#fn31" class="footnote-ref" id="fnref31" role="doc-noteref"><sup>31</sup></a></p>
<p>본 연구에서는 넓은 범위의 물리화학적 속성과 소실 거동을 포괄하기 위해 TH1 및 LCB1 전하 생체 분포 하위 패널의 6종 Fc 융합 단백질을 분석했습니다. 낮은 세포 비특이성과 높은 FcRn 재활용 효율을 가진 항체 참조군으로 Fc-감마 이펙터 기능이 손상된 Fc 스캐폴드 기반의 우스테키누맙 연구용 아날로그(SEFL2 수정 우스테키누맙)를 포함시켰습니다.<a href="#fn32" class="footnote-ref" id="fnref32" role="doc-noteref"><sup>32</sup></a> 양성 Fc 융합 변이체 두 가지 모두 매우 낮은 FREM 점수를 나타내어 양전하가 hFcRn 재활용 효율에 상당한 영향을 미침을 확인했습니다(그림 5F, SSB-I). 음성 TH1 및 LCB1 단백질은 Fc 융합체 중 가장 높은 FREM을 보였으며, 특히 산성 pI TH1 돌연변이체는 SEFL2 수정 우스테키누맙과 재활용 효율에서 정량적 차이가 없었습니다. 일반적으로 전하가 양의 방향으로 갈수록 비특이성이 높아져 FREM이 감소했으나, 중성 근처 LCB1 단백질은 예외였습니다. 중성 근처 LCB1 Fc 융합체는 염기성 pI 돌연변이체에 비해 세포 비특이성이 낮음에도 불구하고(그림 S2B 및 SSE), 재활용 출력은 더 양전하를 띤 대조군보다 약간 더 낮았습니다(그림 SSC,H). 이러한 종합적인 결과로부터 노출된 양전하로 인해 발생하는 높은 세포외 및 세포 내 비특이성이 NSE를 유도하고 FcRn 트래피킹 역학을 저해함으로써 Fc 융합 단백질의 제거율에 해로운 영향을 미친다고 결론지었습니다. 또한 NSE 수치나 FcRn 매개 재활용 능력 저하만으로는 매우 음의 알짜 전하를 가진 Fc 융합 단백질의 상승된 마우스 CL을 설명할 수 없었습니다.</p>
<p>이러한 결과로부터 몇 가지 결론을 도출할 수 있습니다. 첫째, 고도의 음전하 Fc 융합 단백질의 CL 증가를 주도하는 기전은 양전하 단백질과 구별됩니다. 이는 CL이 높은 분자를 식별하기 위해 비특이성 평가를 활용할 때 고도로 음이온성인 단백질에 대해서는 그 유용성이 제한됨을 의미합니다. 둘째, 계산된 전역 전하 기술자만으로는 세포 비특이적 행동에 대한 정밀한 정보를 제공할 수 없었습니다. 각 단백질 스캐폴드 시리즈 내에서 양전하가 낮을수록 NSE가 감소하는 보존된 경향이 발견되었지만, 그 감소 폭을 예측하기는 어려웠습니다. 이는 항체 알짜 전하와 Fc 융합체 알짜 전하 값을 함께 플롯했을 때 인 실리코-인 비트로 관계가 전혀 나타나지 않은 것에서 더욱 두드러집니다(그림 S4A). 이러한 관찰은 국소적 정전기-세포 상호작용을 더 잘 이해하기 위해 보다 정교한 전하 기술자가 필요함을 시사합니다.<a href="#fn33" class="footnote-ref" id="fnref33" role="doc-noteref"><sup>33</sup></a> 또한 기술자-NSE 관계가 스캐폴드 내 연구에서도 항상 정비례하는 것은 아니었습니다. 이러한 결과는 전임상 항체 세트의 점 돌연변이 유도체들 사이에서는 알짜 전하와 NSE 간의 강한 경향성이 관찰되었으나, 더 넓은 항체 패널을 함께 평가했을 때는 그렇지 않았던 우리의 이전 연구 결과와 부합합니다.<a href="#fn34" class="footnote-ref" id="fnref34" role="doc-noteref"><sup>34</sup></a> 이는 Fc 단백질의 인 비보 CL 거동을 파악하기 위해 전하 특성이 세포의 단백질 처리 방식에 미치는 영향을 실험적으로 측정하는 것이 필수적임을 강조합니다.</p>
<p>그림 5. 비특이적 세포내섭취 및 인간 FcRn 재활용은 증가된 양전하에 의해 바람직하지 않은 영향을 받는다. 비특이적 세포내섭취(NSE) 측정은 pH 5.8 (A) 및 pH 7.4 (B) 배양 조건에서 CHO-K1 세포를 사용하여 수행되었습니다. 형광 접합 항-인간 Fc 항체와 유세포 분석법을 사용한 면역 염색을 통해 단일 세포 관련 Fc 융합 단백질(즉, 표면 및 세포 내부)을 검출했습니다(단백질당 N=3-4). 집단 중앙값 형광 강도는 항체 결합 용량(ABCs)으로 변환되었으며, 이는 실험 간 비교를 용이하게 하기 위한 정량적 접근 방식입니다. 두 pH 값에서의 평균 CHO-K1 ABC와 마우스 제거율(CL) 사이에서 유의미한 스피어만 상관관계가 측정되었습니다(pH 5.8: 스피어만 <span class="math inline">\(r = 0.55\)</span>, <span class="math inline">\(p &lt; 0.001\)</span>; pH 7.4: 스피어만 <span class="math inline">\(r = 0.54\)</span>, <span class="math inline">\(p &lt; 0.001\)</span>). (C) 마우스 CL과 가장 강력하게 상관관계가 있는 세 가지 기술자인 서열 기반 pI, 알짜 전하 및 양성 단백질 패치의 총 표면적 백분율(patch_pos_%)과 CHO-K1 ABC 사이의 관계를 평가했습니다. 세 가지 플롯 모두 유의미한 스피어만 상관관계를 가진 S자형(sigmoidal)을 나타냈으며, 각 관계는 알짜 전하 -5.0 이상의 단백질에서 정체되었습니다. pI_seq, 알짜 전하 및 patch_pos_%의 스피어만 r은 각각 0.71 (<span class="math inline">\(p &lt; 0.0001\)</span>), 0.70 (<span class="math inline">\(p &lt; 0.0001\)</span>) 및 0.67 (<span class="math inline">\(p &lt; 0.0001\)</span>)이었습니다. (D) CL을 주도하는 기전을 더 잘 이해하기 위해 그림 2에 표시된 것과 동일한 알짜 전하 빈에 대해 CHO-K1 ABC를 플롯했습니다. 알짜 전하 -5.0 위에서만 상승된 NSE가 관찰되었으며, 이는 강한 양성 및 음성 단백질에 대해 두 개의 별개의 제거 경로가 있음을 시사합니다. (E) 개별 단백질 모달리티에 대해 알짜 전하와 CHO-K1 ABC를 비교한 결과, 합산 플롯보다 훨씬 더 명확한 관계가 입증되었습니다. (F) TH1 및 LCB1 전하 시리즈의 인간 FcRn 재활용 효율 지표를 얻기 위해 세포 FcRn 재활용 연구를 수행했습니다. 이펙터 기능이 없는 연구용 항체 우스테키누맙(SEFL2 수정 우스테키누맙)을 대조군으로 사용했습니다.</p>
<ol type="A">
<li><p><img src="images/cc31ce6e3bddfa4e852d80a555f1195a7b4a68d3987946691ec00afe7cd5acc7.jpg" class="img-fluid"></p></li>
<li><p><img src="images/1325d3c990dd6e8b793171499efecf80c0b7bcc1e2ecc4c6a2ad97bc3371cac2.jpg" class="img-fluid"></p></li>
<li><p><img src="images/b54771154305ab4cfa3a7b4efdf869221b23166c01e67c7783ece5cb5daefac6.jpg" class="img-fluid"><br>
<img src="images/c718387b710e5ce94be4b813e5bc02bdf6377e06d4da470ed1ee7b580db04465.jpg" class="img-fluid"> <img src="images/950d7240a33cea3985d15835f52c1d8872ad4470e7a82ac773d4bb8f2747a3ad.jpg" class="img-fluid"></p></li>
<li><p><img src="images/2b4a928e49d2eef0c35c841c3bb0dc755a79ff344600f14fc941dafb27adbdca.jpg" class="img-fluid"> <img src="images/c87a721b0a2bbc6e9432406c69385d62ea5d9ff939d122fa6058c46c164ae9a2.jpg" class="img-fluid"></p></li>
<li><p><img src="images/878fd3ed1ac68303b6c236ad23b7b618d5aa9e5ebc483e876d0ffc085df7397c.jpg" class="img-fluid"></p></li>
<li><p><img src="images/c457430d7102507b61e9d4d4472b32581f3ef04e642cf46c2bbe8b7abb534eb3.jpg" class="img-fluid"><br>
<img src="images/a5d85e97fb54d678cd9312b1fa657807438b2a7cf8f7b17ef896b2bf17f6c5dc.jpg" class="img-fluid"> <img src="images/0b254d176f13d0c3dd9521046aff4fc33fc7b37531e53c7737808fc3021c787c.jpg" class="img-fluid"> <img src="images/abf99bd80c9d4e5c97de45a7e55a38ef48a8207218fb98feddcdbec2c302b38b.jpg" class="img-fluid"> <img src="images/4370e354317ae0387471c6d5e19c488290fd984e6a12d742d6d2efe69712246e.jpg" class="img-fluid"></p></li>
</ol>
</section>
<section id="fc-융합체의-비표적-조직-축적에서-전하의-역할" class="level2">
<h2 class="anchored" data-anchor-id="fc-융합체의-비표적-조직-축적에서-전하의-역할">Fc 융합체의 비표적 조직 축적에서 전하의 역할</h2>
<p>제작된 Fc 융합 단백질의 CL 결정 요인을 평가한 후, 전하 변이에 따른 조직 정체 증가를 주도하는 기전적 요인을 이해하고자 했습니다. 치료용 단백질 생체 분포의 첫 번째 주요 장벽은 혈관 내피와의 상호작용 및 이에 따른 혈관외 유출(extravasation)이며, 이는 장기 및 내피의 이질성으로 인해 조직 유형마다 다릅니다.<a href="#fn35" class="footnote-ref" id="fnref35" role="doc-noteref"><sup>35</sup></a>[^80-84] 간, 신장, 비장 외에도 피부와 골격근이 항체 이화작용 및 IgG 항상성에 중요한 장기로 식별되었습니다.[^73-75]<a href="#fn36" class="footnote-ref" id="fnref36" role="doc-noteref"><sup>36</sup></a>[^85-87] 이 두 조직 유형은 창이 없는(nonfenestrated) 연속 내피층을 포함하고 있습니다.<a href="#fn37" class="footnote-ref" id="fnref37" role="doc-noteref"><sup>37</sup></a><a href="#fn38" class="footnote-ref" id="fnref38" role="doc-noteref"><sup>38</sup></a> 일반적으로 내피 내 단백질의 정점-기저부(apical-to-basolateral) 투과성은 농도 구배에 따라 세포 사이의 틈을 통한 파라세포 이동(paracellular movement) 또는 세포를 통과하는 횡단세포 유속(transcellular flux)을 통해 발생할 수 있습니다.<a href="#fn39" class="footnote-ref" id="fnref39" role="doc-noteref"><sup>39</sup></a>[^88-96] 단백질의 분자 반경이 증가함에 따라 내피 투과성이 감소하다가 혈청 알부민 크기 근처에서 정체되며, 그 이상의 크기 증가에 대해서는 투과성 차이가 거의 없다는 관계가 기 구축된 바 있습니다.<a href="#fn40" class="footnote-ref" id="fnref40" role="doc-noteref"><sup>40</sup></a> 거대 분자의 내피 투과성에 대한 이러한 형태학적 및 기능적 연구들을 종합해 볼 때, 현재 생성된 Fc 융합 단백질(분자량 범위 <span class="math inline">\(\approx 55 \sim 75\mathrm{kDa}\)</span>)의 경우 연속 내피층에서의 주된 혈관외 유출 경로는 횡단세포 이동일 것으로 예상되며, 이는 수용체 의존적 또는 독립적 방식의 비특이적 세포내섭취 이후에 발생할 수 있습니다.<a href="#fn41" class="footnote-ref" id="fnref41" role="doc-noteref"><sup>41</sup></a>[^88-96] 따라서 전하 매개로 인한 내피 NSE 또는 세포 내 트래피킹의 변화는 이러한 내피 유형 내의 혈관 투과성 변화로 이어질 수 있습니다. 그러나 면역글로불린 G 항체 및 Fc 기반 치료제의 혈관외 유출에서 내피 FcRn의 역할은 아직 명확히 정의되지 않았습니다.<a href="#fn42" class="footnote-ref" id="fnref42" role="doc-noteref"><sup>42</sup></a>[^97-98]</p>
<p>간질 공간으로 들어가면 Fc 융합 단백질은 여러 물리적 및 물리화학적 측면의 영향을 받을 수 있는 확산 및 대류 수송을 거치게 됩니다.[^99-104] 글리코사미노글리칸은 간질 세포외 매트릭스의 주요 구성 요소로 알짜 음전하를 띠고 있으며, 이는 음이온성 또는 양이온성 단백질과의 척력 또는 인력으로 이어질 수 있습니다.<a href="#fn43" class="footnote-ref" id="fnref43" role="doc-noteref"><sup>43</sup></a>[^101-106] 조직 공간으로부터의 소실은 부분적으로 림프관 배수(lymphatic drainage)를 통한 유출 및/또는 상주 간질 세포에 의한 세포 내 이화작용에 기인합니다.<a href="#fn44" class="footnote-ref" id="fnref44" role="doc-noteref"><sup>44</sup></a><a href="#fn45" class="footnote-ref" id="fnref45" role="doc-noteref"><sup>45</sup></a>[^86-87] Fc 융합 단백질과 이러한 다양한 조직 구성 요소 사이의 정전기적 상호작용은 간질의 세포 및 구조적 특징과의 상호작용을 변화시킴으로써 순 축적량과 전체적인 분포의 변화를 초래할 수 있습니다. 따라서 전하 매개 영향은 혈관외 유출과 결합하여 특정 조직으로의 진입, 통과 및 유출에 효과적으로 영향을 미칠 수 있습니다.</p>
<p>우리는 TH1 전하 하위 시리즈의 다양한 물리화학적, 세포적 및 소실 특성을 활용하여 혈관 및 간질 공간이 뚜렷이 구분되는 3D 인 비트로 미세 혈관 네트워크(MVN) 모델 내에서 상세 조사를 수행했습니다.<a href="#fn46" class="footnote-ref" id="fnref46" role="doc-noteref"><sup>46</sup></a> 이 미세 생리학 시스템(MPS)은 공동 배양된 내피 세포(HUVECs, GFP 안정 발현)와 기질 세포(인간 폐 섬유아세포)가 관류 가능한 연속 MVN으로 자가 조립되도록 촉진하며, 이는 실제 체내 값과 보다 유사한 거대 분자 투과성을 나타내는 당질층(glycocalyx)과 밀착 연접(tight junction)을 보유하고 있습니다.</p>
<p>표 2. 표지되지 않은 분자 및 형광 접합 분자 대 1X FITC 및 Dylight650 표지 분자의 등전점 비교</p>
<table>
<tbody><tr>
<td rowspan="2">
분자
</td>
<td colspan="3">
pI
</td>
</tr>
<tr>
<td>
표지되지 않음
</td>
<td>
DL650
</td>
<td>
FITC
</td>
</tr>
<tr>
<td>
Near-Neutral-TH1
</td>
<td>
6.13
</td>
<td>
5.42
</td>
<td>
5.77
</td>
</tr>
<tr>
<td>
Basic-TH1
</td>
<td>
7.92
</td>
<td>
6.72
</td>
<td>
NA
</td>
</tr>
<tr>
<td>
Acidic-TH1
</td>
<td>
4.78
</td>
<td>
4.70
</td>
<td>
4.91
</td>
</tr>
</tbody></table>
<p>표 3. 표지되지 않은 분자 대 0.5X Dylight650 또는 0.5X FITC 표지 분자의 등전점 비교</p>
<table>
<tbody><tr>
<td rowspan="2">
분자
</td>
<td colspan="3">
pI
</td>
</tr>
<tr>
<td>
표지되지 않음
</td>
<td>
DL650
</td>
<td>
FITC
</td>
</tr>
<tr>
<td>
Near-Neutral-TH1
</td>
<td>
6.18
</td>
<td>
NA
</td>
<td>
NA
</td>
</tr>
<tr>
<td>
Basic-TH1
</td>
<td>
8.02
</td>
<td>
6.96
</td>
<td>
7.16
</td>
</tr>
<tr>
<td>
Acidic-TH1
</td>
<td>
4.90
</td>
<td>
NA
</td>
<td>
NA
</td>
</tr>
</tbody></table>
<p>먼저 FRAP을 통해 확산 계수와 비이동 분율을 정량화함으로써 간질 내에서 서로 다른 전하를 가진 단백질의 거동을 비교했습니다. TH1 전하 패널을 FITC로 표지하고 접합된 단백질의 pI를 icIEF로 분석했습니다(표 2 및 3, 그림 S6). 미세 유체 장치 내에서 FITC 표지된 TH1 단백질을 24시간 동안 미리 인큐베이션하여 간질 평형을 이룬 뒤, TRITC 표지된 70kDa 덱스트란을 주입하여 혈관 구획을 식별했습니다. 이후 간질 공간 내 관심 영역에 대해 즉시 FRAP을 수행했습니다(그림 6A,B). 산성 pI를 가진 TH1 Fc 융합 단백질은 중성 근처 및 염기성 TH1 변이체에 비해 유의하게 높은 확산성을 보였습니다(그림 6C, Kruskal-Wallis 테스트 후 Dunn의 다중 비교 결과 중성 근처 TH1 대비 <span class="math inline">\(*p &lt; 0.05\)</span>). 평가된 모든 TH1 Fc 융합체는 유사한 비이동 분율을 나타냈으나(그림 6D), 염기성 pI TH1 단백질로 처리된 MVN 샘플에서는 간질 공간 전체에 걸쳐 가시적인 침착이 관찰되는 현격한 차이가 있었습니다(그림 6B, 화살표 머리). 또한 MVN이 없는 상태에서 FRAP 측정을 반복했을 때 전하에 따른 확산성 및 비이동 분율의 유의미한 변화가 관찰되었습니다(그림 S7). 이는 MVN에 의한 매트릭스 리모델링이 일어나고 있음을 시사하며, 인간 조직과 밀접하게 유사한 3D 세포 구조 내에서 이러한 매개변수를 평가하는 것의 중요성을 강조합니다.</p>
<p>다음으로 MVN 내 TH1 전하 하위 시리즈의 혈관-간질 투과성을 측정했습니다(그림 6E). 다만 사용된 MPS의 한계로 인해 장치 채널을 감싸는 내피 단층의 투과성이 3D MVN보다 실질적으로 높게 나타납니다.<a href="#fn47" class="footnote-ref" id="fnref47" role="doc-noteref"><sup>47</sup></a> 따라서 TH1 투과성 실험은 MVN 투과성이 지배적인 거대 분자 유속의 정량화를 용이하게 한다고 이전에 밝혀진 12분 동안 수행되었습니다.[^60-61]<a href="#fn48" class="footnote-ref" id="fnref48" role="doc-noteref"><sup>48</sup></a> HUVECs 내의 녹색 형광 단백질과 중첩을 피하기 위해 FITC 대신 스펙트럼 및 광안정성 특성이 우수한 DL650 형광체를 선택했습니다. DL650 표지는 FITC와 동일한 비율로 시도되었으나, icIEF 결과 양이온성 TH1 Fc 융합체의 pI에 DL650이 더 큰 영향을 미치는 것으로 나타났습니다(표 2, 그림 S6). 따라서 최종 DL650 양은 이 단백질에 대해서만 1:1 미만으로 줄였습니다. 유사한 분자량을 가진 참조 분자로 70kDa TRITC-덱스트란을 각 DL650 표지 TH1 단백질과 함께 주입했습니다. 염기성 pI TH1 Fc 융합체의 투과성은 산성 pI TH1보다 2배 높았고 중성 근처 pI 단백질의 절반 수준이었습니다. 그러나 테스트된 모든 TH1 Fc 융합체 간의 투과성 차이는 통계적으로 유의하지 않았으며 70kDa 덱스트란 대조군의 실험적 변동 범위 내에 있었습니다(그림 6F).</p>
<p>FRAP 분석 중 관찰된 MVN 내 단백질의 국소적 축적을 더 잘 이해하기 위해 DL650 표지 TH1 단백질을 총 60분 동안 배양했습니다(그림 6G). 모든 TH1 단백질은 실험 과정 동안 내피 세포(EC)와의 공동 위치(colocalization)를 보였으며, 특히 CHO-K1 NSE 분석 결과와 일치하게 양성 TH1 그룹에서 현저히 높은 형광 신호가 관찰되었습니다(그림 S2B). 더욱이 양이온성 TH1 Fc 융합체는 MPS의 간질 및 혈관 부분 전체에 걸쳐 잔류하는 것처럼 보였습니다. 앞서 언급한 채널 단층으로 인한 한계로 인해 60분 배양 동안 MVN 투과성 차이가 높은 간질 신호에 기여했는지 여부는 확정할 수 없습니다. 그러나 이러한 MPS 관찰 결과는 변이된 양전하 특성을 가진 Fc 융합 단백질의 경우 연속 내피층에서의 축적에 세포 정체(cellular retention)가 중요한 요소임을 뒷받침합니다. MVN 결과와 다른 모든 세포 평가 결과를 종합해 볼 때, 우리는 향상된 NSE와 비효율적인 FcRn 재활용이 양이온성 LCB1 및 TH1 단백질의 조직 축적 증가를 위한 일반적인 기전이라고 제안합니다.</p>
</section>
<section id="리포좀-클로드로네이트를-통한-대식세포-고갈은-lcb1-fc-융합-단백질의-비장-축적-증가를-초래한다" class="level2">
<h2 class="anchored" data-anchor-id="리포좀-클로드로네이트를-통한-대식세포-고갈은-lcb1-fc-융합-단백질의-비장-축적-증가를-초래한다">리포좀 클로드로네이트를 통한 대식세포 고갈은 LCB1 Fc 융합 단백질의 비장 축적 증가를 초래한다</h2>
<p>통합적인 세포 분석 결과는 음이온성 및 양이온성 Fc 융합 단백질이 서로 다른 제거 및 분포 기전을 가짐을 시사하며, 양이온성 분자에게는 정전기적으로 유도된 비특이성이 핵심 요소임을 보여주었습니다. 그러나 음전하 변이체들의 변화된 소실을 유발하는 원인에 대해서는 여전히 상세한 이해가 부족했습니다. 가능한 세포학적 설명 중 하나는 대식세포를 포함한 다양한 세포에서 발현되는 스캐벤저 수용체(SRs)에 의한 수용체 매개 내부화가 혈액으로부터의 신속한 제거를 유도할 것이라는 점입니다. SR은 광범위한 리간드 특이성을 나타내어 내인성 및 외인성 물질의 결합 및 제거에 중요한 역할을 합니다.[^107-108] SR의 특징 중 하나는 폴리음이온성 기질을 인식한다는 점이며, 이는 부분적으로 3차 구조의 용매 인터페이스에서의 최적화된 전하 분포에 기인합니다.[^108-113] 이러한 기능은 음이온성 Fc 융합 단백질의 특이적 대식세포 내부화를 초래할 수 있으며, 이는 우리의 비특이적 세포 연구에서는 재현되지 않았을 가능성이 큽니다. 또한 대식세포는 전하와 무관하게 고도의 세포내섭취 특성으로 인해 전체 Fc 융합 단백질 소실에 기여할 수도 있습니다.<a href="#fn49" class="footnote-ref" id="fnref49" role="doc-noteref"><sup>49</sup></a>[^86-87]<a href="#fn50" class="footnote-ref" id="fnref50" role="doc-noteref"><sup>50</sup></a></p>
<p>그림 6. 과도한 음전하 또는 양전하를 가진 단백질은 서로 다른 기전을 통해 조직 축적 증가를 나타낸다. (A, B) TH1 pI 하위 시리즈를 FITC로 표지했습니다. MVN 장치 내에서 단백질을 24시간 동안 배양하여 간질 평형을 이룬 후 베이스라인 이미지를 획득했으며, 흰색 화살표로 표시된 것처럼 염기성 pI 단백질에서만 유의미한 간질 축적이 입증되었습니다. (C) FRAP 연구를 통해 얻은 확산성 측정 결과, 가장 음으로 대전된 산성 pI 단백질의 확산 속도가 다른 모든 분석 물질에 비해 유의하게 높음이 확인되었습니다. (D) 대표적인 FRAP 실험 및 간질 내 비이동 분율 계산에 사용된 회복 곡선. 양전하가 증가함에 따라 비이동 분율이 증가하는 경향이 관찰되었습니다. (E) MVN 장치 내 미세 혈관 투과성 연구를 위한 모식도. 형광 정량을 용이하게 하기 위해 단백질을 DL650으로 표지했습니다. (F) 어떤 단백질 사이에서도 투과성의 유의미한 차이는 관찰되지 않았습니다. 70kDa TRITC 덱스트란을 MVN 무결성을 위한 내부 대조군으로 사용했습니다. (G) 초기 관류 60분 후에 획득한 공초점 이미지 결과, 염기성 TH1 단백질의 유의미한 간질 및 내피 축적이 밝혀졌습니다.</p>
<ol type="A">
<li><p><img src="images/74f2e2a38d7f56d3819cd4b862501ad3f1cbbd5099a7280c805324dc62f97e58.jpg" class="img-fluid"><br>
<img src="images/5d238d36ff1057a3977c4e991af12fc2a7728aa62ab4535e9b2aea7d1ec1cb8e.jpg" class="img-fluid"> <img src="images/e12b309c838f5ff24429efbd0bab615919e177344e1d7157743a4a6555fc389d.jpg" class="img-fluid"></p></li>
<li><p><img src="images/c4131a561f5183a92cc46950d8a43332b07ff0bc993dd72070f22293bd7fb493.jpg" class="img-fluid"><br>
<img src="images/bd136df13a62d55cb41cf4766769c7bfe256d4b2a30f58f37c22963f90aa076d.jpg" class="img-fluid"> <img src="images/624d5cbece9b856fca786987d312d396e87e1cdb02e3c63f2a4e594108031264.jpg" class="img-fluid"> <img src="images/dd93692133a58758bc153e3b85b3c4890cca6486e61d97420a99a17a67090167.jpg" class="img-fluid"></p></li>
<li><p><img src="images/d8ddf0c84b035353c50d920119e763f5e92bdcd691d994a4e15136cd045b983c.jpg" class="img-fluid"></p></li>
<li><p><img src="images/233703c722b3be77375ab3e2a5cff22272d9f62557ffcbe57276811c07e29388.jpg" class="img-fluid"></p></li>
<li><p><img src="images/dcb926a3a36f497afb6044cc97a63e1bb8c2eea6cbcd9103a5387eee74b7c625.jpg" class="img-fluid"></p></li>
<li><p><img src="images/0a2ace25d995433a557f76a2bf82a9345729a6e215533e9180ab97f8c8955e15.jpg" class="img-fluid"></p></li>
<li><p><img src="images/ccac9a83a0cddc104b8a39f44d45004e1fb4208e22b36c98ae3b3d3831e6ceef.jpg" class="img-fluid"><br>
<img src="images/031d86fb72087376e3a07c12460b3c6c8887e79198503fa791e0dbea35cf6b90.jpg" class="img-fluid"> <img src="images/c3d88159cdba7ca6677a9a06b32eeb070354a7bcbaf0a37cc020666a6be1073b.jpg" class="img-fluid"> <img src="images/bc25a5b3fa64201605943182a464be61e658e03f0c246321292012b19164598b.jpg" class="img-fluid"> <img src="images/d30b0e57498b415702b4965697745d3b3fe4e32bec5b024527c6cea1a42ed753.jpg" class="img-fluid"> <img src="images/5f03996c7b1dca5116caad30f846d8e5eefa4045aaf68857d70647d7d45aacb1.jpg" class="img-fluid"> <img src="images/2a356c14cee4632d85af305d21408ecc8642b9c9f904e3cc33a74e0078677bc5.jpg" class="img-fluid"></p></li>
</ol>
<p>우리는 리포좀 클로드로네이트를 통한 선택적 고갈을 활용하여 LCB1 전하 하위 세트의 조직 축적 및 전체 CL에서 대식세포의 잠재적 역할을 조사했습니다. 이러한 나노 입자의 생체 분포는 정맥 투여 후 주로 비장, 골수 및 간에 집중됩니다. 노출된 대식세포는 클로드로네이트 리포좀을 식균하여 결과적으로 사멸하게 되지만, 주변 세포 유형은 낮은 투과성과 유리 클로드로네이트의 신속한 제거로 인해 거의 영향을 받지 않습니다.<a href="#fn51" class="footnote-ref" id="fnref51" role="doc-noteref"><sup>51</sup></a><a href="#fn52" class="footnote-ref" id="fnref52" role="doc-noteref"><sup>52</sup></a> 클로드로네이트 및 대조군 리포좀은 3종의 LCB1 하위 세트 단백질 각각을 <span class="math inline">\(2\mathrm{mg/kg}\)</span> 정맥 볼루스 투여하기 2일 전에 주사되었습니다. 전하 하위 시리즈 연구와 조직 유형을 맞추기 위해 투여 후 0.5시간에 혈청, 간, 신장 및 비장을 수집했습니다. 추가로 흡수가 낮을 것으로 예상되는 대조 조직으로 근육을 수집했습니다. 예상된 리포좀 생체 분포와 일치하게, 어떤 LCB1 단백질에 대해서도 대조군과 클로드로네이트 탑재 리포좀 그룹 사이의 혈청 농도나 신장 및 근육의 조직/혈청 비율에서 유의미한 차이는 관찰되지 않았습니다(그림 7A,B). 테스트된 모든 LCB1 단백질의 비장 조직/혈청 비율과 농도는 리포좀 클로드로네이트를 투여받은 마우스에서 증가했으며(그림 7B, C), 이는 단백질 전하와 관계없이 이 조직 내의 순 축적에서 대식세포의 역할을 시사합니다.</p>
<p>그림 7. 리포좀 클로드로네이트 처리는 전체 LCB1 전하 시리즈의 비장 축적 증가를 초래한다. 야생형 C57BL/6J 마우스에 대조군 또는 클로드로네이트 탑재 리포좀을 정맥 볼루스 투여했습니다. 약 48시간 후 LCB1 전하 하위 시리즈를 정맥 투여하고 0.5시간 후에 조직과 혈청을 수집했습니다. (A) 클로드로네이트와 대조군 리포좀 그룹 간에 혈청 농도 차이는 관찰되지 않았습니다(이원 ANOVA 후 Sidak의 다중 비교 결과 ns, 유의성 없음). (B, C) 모든 LCB1 단백질은 대조군에 비해 상승된 비장/혈청 비율(B) 및 비장 농도(C)를 나타냈습니다. 또한 산성 pI LCB1 Fc 융합체의 경우 간/혈청 비율과 간 농도에서 유의미한 차이가 관찰되었습니다. (<span class="math inline">\(^*p &lt; 0.05, ^{**}p &lt; 0.001\)</span>, ns, 유의하지 않음; 이원 ANOVA 후 Sidak의 다중 비교).</p>
<ol type="A">
<li><p><img src="images/df804f55894fc66658b93ac8d363333321596350e81184ed2eef74005b6f1633.jpg" class="img-fluid"></p></li>
<li><p><img src="images/621eaf709727697cde510c158268728ac9d4f426673e41aa1f58d0d228535a90.jpg" class="img-fluid"> <img src="images/b8d368f37106d2a51103a4154c4528fff339ecaf6d700367e225e6f55260d9db.jpg" class="img-fluid"> <img src="images/40a338f8e1eab79212252c34397fee959b256019b546b47df85936e803660dff.jpg" class="img-fluid"></p></li>
<li><p><img src="images/32bb2ffb7f600444aefa3b002471820f70497c27e85504428141c18f59fdd2c2.jpg" class="img-fluid"> <img src="images/ea7f86df32728841b02ea0336a3ae3cd954413e6b1a202a5b76992dc5e6ec6b4.jpg" class="img-fluid"> <img src="images/97e91e7af62e3b288020470f9fdcc0905cc5f20c33b9a75888ab5bb125fe0e38.jpg" class="img-fluid"></p></li>
</ol>
<p>그림 8. 높은 표적 독립적 제거율을 유발하는 전하 주도 세포 기전. Fc 융합 단백질의 노출된 양전하와 세포막의 음이온성 영역 사이의 정전기적 상호작용은 흡착 비특이적 세포내섭취(NSE)를 매개하며, 이는 본 연구에서 Fc 융합체의 마우스 제거율(마우스 내 알려진 결합 파트너가 없으므로 표적 독립적 제거율)과 유의미하고 양의 상관관계를 나타냈습니다. 이는 NSE가 높은 Fc 함유 치료제가 세포당 비특이적으로 내부화되는 초기 양이 더 많아지게 하여, 리소좀 이화작용을 방지하기 위해 성공적인 FcRn 재활용을 거쳐야 하는 부담을 가중시킵니다. 내부화 이후 엔도좀 산성화는 pH 감소에 따른 양전하 증가로 인해 단백질 비특이성을 더욱 강화합니다. LCB1 및 TH1 하위 시리즈의 결과는 산성 pH에서의 세포 비특이성이 높은 NSE를 넘어서는 이유로 효율적인 FcRn 재활용에 해로운 영향을 미친다는 점을 시사합니다. Fc 영역 내부 및 외부의 노출된 양전하가 적절한 FcRn 결합 및 트래피킹 역학을 방해할 가능성이 큽니다. 가능한 원인으로는 FcRn에 결합하지 않거나 심지어 결합한 상태의 Fc 융합 단백질과 엔도좀 막 사이의 비특이적 상호작용, 그리고 세포 표면에서의 부적절한 pH 의존적 FcRn 해리 등이 있습니다. 즉, 높은 NSE를 촉진하는 동일한 요인들이 FcRn-Fc 융합 상호작용의 특이성도 저해하게 됩니다. 결과적으로 더 많은 비표적 세포가 더 많은 단백질을 내부화하고, 손상된 FcRn 역학으로 인해 성공적으로 재활용되는 총량이 줄어들며, 비특이적으로 내부화된 단백질 중 이화작용을 겪는 분율이 커지면서 제거 속도가 빨라집니다. 참고로 Fc 융합체와 hFcRn 상호작용은 해석의 용이성을 위해 단순화하여 표현되었습니다. 상세 내용은 고찰을 참조하십시오. BioRender.com을 사용하여 제작됨.</p>
<p>그림 8. <img src="images/94659527796dfe62a1074cf5cdc16636eca17174417b577c1057ce3608fdca7a.jpg" class="img-fluid"></p>
<p>이러한 결과로부터 우리는 대식세포 매개 내부화가 조사된 단백질의 간 및 비장 진입에 반드시 영향을 미치는 것은 아닐지라도, 3종의 LCB1 Fc 융합체 모두에 대해 비장 조직 공간으로부터의 핵심 제거 요소임을 확인했습니다. 더욱이 음이온성 LCB1 단백질의 간 축적 증가가 유의미하게 나타난 것은, 다른 LCB1 변이체에 비해 이 전하 변이체의 경우 간 내 상주 대식세포가 장기 제거에서 더 큰 비중을 차지할 가능성을 시사합니다.</p>
</section>
</section>
<section id="고찰" class="level1">
<h1>고찰</h1>
<p>항체와 같은 치료용 Fc 단백질의 소실은 표적 매개 및 표적 독립적 과정의 조합에 의해 결정되며, 후자는 종종 간과되지만 마찬가지로 중요한 구성 요소입니다. 본 연구에서는 마우스 내에 알려진 내인성 표적이 없는 데 노보 단백질을 성공적으로 설계 및 제작하여 Fc 융합 단백질의 표적 독립적 소실을 주도하는 기전을 정의하였습니다. 이 패널은 pI 및 표면 패치 구성과 같은 광범위한 생물물리학적 특성을 포함하도록 계획되어 인 비보 및 세포 과정과의 관계를 탐색하였습니다. 본 연구의 결과는 단백질 표면에 노출된 양전하와 음전하를 띤 세포 구성 요소 사이의 정전기적 상호작용으로 인해 발생하는 세포 비특이성이 Fc 융합체 소실의 핵심 요소임을 보여줍니다.</p>
<p>인 실리코 전하 기술자와 제거율 사이의 상관관계는 개별 스캐폴드 내에서는 명확했지만 전체 데이터 세트에서는 그렇지 않았으며, 이는 스캐폴드 의존적인 한계를 강조합니다. 스캐폴드 내 상관관계는 백본 프레임워크가 일정하게 유지될 때 전하 기반 기술자가 미세한 수정에도 민감하게 반응함을 시사합니다. 그러나 스캐폴드 간 상관관계의 상실은 추가적인 스캐폴드 의존적 속성이 CL에 영향을 미침을 나타냅니다. 현재 특징 세트에는 형태 관련 기술자(예: 회전 반경 및 이심률)와 조성 기반 기술자(예: <span class="math inline">\(\alpha\)</span>-헬릭스 및 <span class="math inline">\(\beta\)</span>-시트 함량)가 포함되어 있지만, 본 연구의 제한된 스캐폴드 수를 고려할 때 이들이 PK의 스캐폴드 특이적 결정 요인을 충분히 포착하는지는 불분명합니다. 모델의 일반화 능력을 향상시키기 위해 스캐폴드 레퍼토리를 확장하는 것이 필수적이며, 구조적 기술자의 지속적인 정교화와 기저 생물학적 기전에 대한 깊은 이해를 통해 예측 PK 모델링의 획기적인 발전을 이룰 수 있을 것입니다.<a href="#fn53" class="footnote-ref" id="fnref53" role="doc-noteref"><sup>53</sup></a></p>
<p>표적이 없는 세포에 의한 비특이적 흡수 및 후속 제거는 항체 및 Fc 기반 치료제의 <span class="math inline">\(\mathrm{CL}_{\mathrm{ind}}\)</span>에서 중요한 구성 요소입니다.<a href="#fn54" class="footnote-ref" id="fnref54" role="doc-noteref"><sup>54</sup></a>[^117-120] 본 연구는 전하 매개 비특이성이 NSE가 <span class="math inline">\(\mathrm{CL}_{\mathrm{ind}}\)</span> 상승에 기여하는 정도에 영향을 미친다는 점을 강조합니다(그림 8). 각 Fc 융합 구조 표면의 집중된 양전하는 pH 7.4에서의 상승된 NSE와 유의미한 상관관계가 있었습니다. 양전하 표면 패치가 감소된 항-IL-4R <span class="math inline">\(\alpha\)</span> 항체 점 돌연변이체에서 NSE가 감소함을 보여준 우리의 이전 보고와 결합하여, 치료용 단백질과 세포막 사이의 정전기적 상호작용이 흡착 NSE 속도를 결정하는 데 필수적이라고 결론지었습니다.<a href="#fn55" class="footnote-ref" id="fnref55" role="doc-noteref"><sup>55</sup></a> 그러나 우리는 모든 Fc 융합 단백질에 걸친 NSE 양을 추론하는 데 있어 사용된 인 실리코 전하 기술자의 한계를 확인했으며, 이는 이러한 상호작용의 복잡성을 부각시킵니다. 향후 특정 단백질 스캐폴드 상의 전하 패치 위치에 따른 NSE의 민감도 등 물리화학적 관계를 정교화하는 연구는 이러한 과정을 더 잘 이해하고 NSE와 <span class="math inline">\(\mathrm{CL}_{\mathrm{ind}}\)</span>를 줄이기 위한 단백질 공학 전략을 가이드하는 데 중요할 것입니다.</p>
<p>높은 NSE는 비표적 세포로 더 많은 단백질이 진입하게 하여 이화작용에 의한 분해 확률을 높입니다.<a href="#fn56" class="footnote-ref" id="fnref56" role="doc-noteref"><sup>56</sup></a> 그러나 추가적인 세포 내 기전이 FcRn 발현 세포에서의 Fc 단백질 재활용 효율에 영향을 미칠 가능성이 큽니다. 우리는 다양한 단백질 형태에 걸쳐 용액 pH가 감소함에 따라 세포 비특이성이 강화될 수 있음을 보여주었습니다. 따라서 내부화된 Fc 단백질 중 가용성 분율에서 동적인 변화가 일어나 엔도좀 막에 대한 비특이적 표면 결합 수준이 높아질 수 있으며, 이는 FcRn으로의 접근을 차단할 수 있습니다. 비특이성은 또한 FcRn 결합 자체를 직접적으로 방해할 수도 있습니다. 이전 연구들은 항체 가변 영역이 FcRn과의 pH 의존적 상호작용에 미치는 영향을 지적했으며, 이는 부분적으로 전하 매개 과정에 기인할 수 있습니다.<a href="#fn57" class="footnote-ref" id="fnref57" role="doc-noteref"><sup>57</sup></a> IgG는 FcRn에 결합할 때 여러 컨포메이션을 취할 수 있으며, 1:2의 화학양론적 결합이 기능성의 핵심으로 제안되었습니다.[^122-126] 이러한 결합 구조 내에서 Fab 암(arms)은 FcRn 및 엔도좀 막과 매우 가깝거나 직접 접촉하는 것으로 제안된 바 있습니다.[^125-128] 이러한 시나리오는 FcRn에 결합된 Fc 단백질에 대해서도 pH 의존적인 비특이적 정전기 상호작용이 가능함을 시사합니다. 즉, 중요한 Fc-FcRn 인터페이스 외부나 기저 엔도좀 막과의 부적절한 결합 이벤트가 발생할 수 있습니다. 이러한 결합 거동의 잠재적 결과로는 비정상적인 Fc-FcRn 결합 방향성 및/또는 세포 표면에서의 Fc 단백질 방출 시의 불균형한 pH 의존성 등이 있으며, 이는 결국 이화작용의 증가로 이어질 수 있습니다(그림 8). 이러한 기전적 시사점은 pH 의존적 해리를 통해 항원 결합을 조절하려는 단백질 설계 전략에 영향을 미쳐야 합니다.<a href="#fn58" class="footnote-ref" id="fnref58" role="doc-noteref"><sup>58</sup></a> 그러나 이러한 가설을 확인하고 비특이성이 FcRn 결합에 어떻게 영향을 미치는지 상세히 밝히기 위해서는 구조, 생물물리학 및 세포 도구를 결합한 향후 연구가 필요할 것입니다.</p>
<p>야생형 마우스는 항체 및 Fc 함유 단백질 구조의 안정성, <span class="math inline">\(\mathrm{CL}_{\mathrm{ind}}\)</span> 및 생체 분포를 평가하고 이러한 거동을 주도하는 기저 과정을 연구하는 데 유용한 인 비보 도구입니다.<a href="#fn59" class="footnote-ref" id="fnref59" role="doc-noteref"><sup>59</sup></a><a href="#fn60" class="footnote-ref" id="fnref60" role="doc-noteref"><sup>60</sup></a><a href="#fn61" class="footnote-ref" id="fnref61" role="doc-noteref"><sup>61</sup></a> 야생형 마우스의 주요 단점은 인간 PK 매개변수에 대한 정보 제공 능력이 마우스 FcRn과 인간 Fc 영역 사이의 종 특이적 결합 차이로 인해 본질적으로 제한된다는 점입니다.<a href="#fn62" class="footnote-ref" id="fnref62" role="doc-noteref"><sup>62</sup></a> 형질전환 인간 FcRn 마우스 모델은 인간 FcRn과 인간 Fc의 결합을 더 적절하게 보존하며 인간 소실 특성에 대한 예측 능력이 더 높은 것으로 나타났으므로, 향후 마우스와 인간 PK 매개변수 사이의 보다 직접적인 인 비트로-인 비보 상관관계를 구축하려는 연구에 사용될 가치가 있습니다.[^131-133]</p>
<p>MVN 연구는 비특이성이 연속 내피층 내의 일반적인 단백질 이동에 어떻게 영향을 미칠 수 있는지 조사하기 위해 3D 세포 모델을 도입했습니다. 시스템에 미세 혈관이 존재할 때 중성 근처 및 염기성 pI를 가진 TH1 단백질 사이에서 간질 비이동 분율이나 확산 속도의 유의미한 차이는 측정되지 않았습니다. 또한 TH1 변이체 간에 정점-기저부 MVN 투과성의 측정 가능한 차이도 관찰되지 않았습니다. 이러한 인 비트로 도구를 사용한 발견은 간질 공간으로의 변화된 진입이나 이동이 연속 내피 내 조직 축적의 주요 요인이 아닐 수 있음을 나타냅니다. 간질 평가의 한 가지 한계는 조직 유형에 따라 매트릭스가 크게 다를 수 있다는 점이며, 사용된 MVN 모델이 대안적인 세포외 매트릭스 구성을 완전히 재현하지 못할 수 있습니다.<a href="#fn63" class="footnote-ref" id="fnref63" role="doc-noteref"><sup>63</sup></a>[^101-106]<a href="#fn64" class="footnote-ref" id="fnref64" role="doc-noteref"><sup>64</sup></a> 인 비트로 투과성 차이가 관찰되지 않은 한 가지 가능성은 TH1 단백질의 파라세포 MVN 수송이 횡단세포 이동을 압도할 정도로 발생했을 수 있다는 점입니다. 두 번째 가능성은 세포 내 트래피킹의 변화로 인해 양이온성 TH1 단백질의 기저부 출현이 지연되었거나 소낭 막 해리 역학이 수정되었을 수 있으며, 두 과정 모두 연구된 시간 범위 내에서 증가된 EC 외세포유출(exocytosis)을 포착하기에는 너무 느렸을 수 있습니다.<a href="#fn65" class="footnote-ref" id="fnref65" role="doc-noteref"><sup>65</sup></a><a href="#fn66" class="footnote-ref" id="fnref66" role="doc-noteref"><sup>66</sup></a> 따라서 우리는 이러한 과정 중 하나가 인 비보에서 양전하 TH1 단백질의 일반적인 축적에 기여하는 요인일 가능성을 배제할 수 없습니다.</p>
<p>MVN 관류 후 이미징 결과, 실험 시간 동안 모든 TH1 단백질이 EC와 연관성을 보였으며 특히 양성 TH1 변이체가 가장 높은 양으로 축적되었습니다. 이러한 데이터에 대한 한 가지 해석은 EC가 혈관을 성공적으로 통과할 수 있는 단백질의 분율을 결정하는 중추적인 역할을 한다는 것입니다. 따라서 정전기적으로 유도된 비특이성에 의한 EC 내부화 강화가 증가된 EC 정체 및 장벽을 가로지르는 순 유속 감소로 상쇄될 수 있습니다. 조직 공간 내에서도 동일한 비특이적 과정이 모든 간질 세포 내에서 발생할 수 있습니다. 따라서 우리의 2D 및 3D 배양 결과는 혈관 및 간질 세포 정체가 FcRn 발현 세포에서도 전하 매개 비특이성을 가진 Fc 함유 단백질의 조직 축적에 중추적인 요소임을 입증합니다. 이러한 결론은 내피 및 비혈관 세포 유형을 IgG 소실의 핵심 요소로 간주한 이전 보고들과 일치합니다.[^85-87][^136-139] 또한 데이터로부터 EC가 항체 기반 및 Fc 치료 모달리티에 대한 간질 단백질 농도의 중추적인 조절자임이 분명합니다.</p>
<p>그러나 여전히 많은 질문이 남아 있습니다. 연속 내피 내에서 FcRn은 어떤 역할을 하는가? 가로세포흐름을 촉진하는가? 아니면 루멘-루멘 재활용을 통해 혈관 단백질 농도를 유지함으로써 가로세포흐름을 방해하는가? 혹은 FcRn이 유의미한 역할을 전혀 하지 않는 것인가?<a href="#fn67" class="footnote-ref" id="fnref67" role="doc-noteref"><sup>67</sup></a><a href="#fn68" class="footnote-ref" id="fnref68" role="doc-noteref"><sup>68</sup></a>[^140-141] 정확히 전하에 의해 EC 트래피킹과 순 단백질 투과성이 어떻게 영향을 받는가?<a href="#fn69" class="footnote-ref" id="fnref69" role="doc-noteref"><sup>69</sup></a> 이러한 질문들과 더불어 많은 미지의 문제들은 치료 분자의 혈관외 유출을 향상시키기 위한 새로운 기술로 이어질 수 있는 EC를 통한 Fc 단백질의 횡단세포 이동(즉, 상피가 아닌 내피)을 지속적으로 탐구할 필요성을 시사합니다.<a href="#fn70" class="footnote-ref" id="fnref70" role="doc-noteref"><sup>70</sup></a></p>
<p>고도로 음이온성인 Fc 융합 단백질의 증가된 혈청 제거 및 조직 축적을 유발하는 정확한 기전은 여전히 불분명합니다. 클로드로네이트 탑재 리포좀 실험은 평가된 모든 LCB1 전하 변이체의 비장 축적에 대식세포가 기여함을 시사했습니다. 이 실험 설계는 SR이 전체 소실에 관여하는지를 직접 조사하지는 않았다는 한계가 있습니다. 오히려 SR을 발현하는 세포 유형의 역할을 뒷받침하는 초기 데이터를 제공했습니다. 잠재적 후보군의 범위(예: stabilin 1 및 2, STAB1, STAB2; SR class A, MSR1; 렉틴 유사 산화 저밀도 지질단백질 수용체-1, LOX1)를 고려할 때, 표면 전하 특성이 Fc 융합체의 SR 매개 세포내섭취에 미치는 영향을 정밀하게 평가하는 전용 연구가 향후 필요할 것입니다. 이러한 연구는 특이성을 입증하기 위한 기 알려진 음이온 리간드와의 인 비트로 및 인 비보 경쟁 실험,<a href="#fn71" class="footnote-ref" id="fnref71" role="doc-noteref"><sup>71</sup></a>[^143-144] 세포 기반 마이크로어레이 결합 분석과 같은 유전학 기술,<a href="#fn72" class="footnote-ref" id="fnref72" role="doc-noteref"><sup>72</sup></a> 그리고 다른 SR 발현 세포 유형(예: 간 시누소이드 EC)에 대한 조사 등을 포함해야 합니다.<a href="#fn73" class="footnote-ref" id="fnref73" role="doc-noteref"><sup>73</sup></a> 또한 음이온성 Fc 융합 단백질 인식에 관여하는 SR의 다양성은 리포좀 클로드로네이트 투여 후 LCB1 혈청 농도에서 관찰 가능한 변화가 없었던 이유가 교차 리간드 인식 및 후속적으로 하나 이상의 대안적 세포 유형에서 발생한 보상 작용 때문이었을 가능성도 시사합니다.</p>
<p>SR 외에도 고도로 음이온성인 Fc 융합 단백질의 상승된 CL에 대한 두 번째 가능한 기전은 신장 제거 증가일 수 있습니다. 일반적으로 Fc 융합 단백질의 신장 제거는 사구체 여과, 근위 세관 재흡수, 루멘 또는 세포 내 이화작용 및 소변 배설로 구성됩니다.<a href="#fn74" class="footnote-ref" id="fnref74" role="doc-noteref"><sup>74</sup></a> 알부민의 경우처럼 사구체에서 여과된 대부분의 Fc 단백질을 근위 세관에서 내부화한 뒤 혈관으로 다시 FcRn 매개 가로세포흐름을 시킬 것으로 예상됩니다.[^148-149] 따라서 여과량, 근위 세관 내부화 또는 근위 세관 FcRn 재활용 효율의 변화는 신장 제거를 증가시킬 것으로 예상됩니다. 사구체 전하 선택성 개념에 따르면 음이온성 단백질의 사구체 여과는 양이온성 대조군보다 낮을 것으로 예상됩니다.[^150-154] 별개의 가능성으로는 음이온성 단백질의 수력학적 크기나 전체적인 유연성의 보다 극적인 변화가 포함될 수 있으며, 이는 이전에 바이오 의약품의 여과에 영향을 미치는 것으로 밝혀진 바 있습니다.<a href="#fn75" class="footnote-ref" id="fnref75" role="doc-noteref"><sup>75</sup></a> 내부화 측면에서, 우리는 단백질의 정전기적 표면 특성이 근위 세관 상피 세포에 의한 수용체 의존적 및 독립적 세포내섭취에 미치는 영향을 규명한 상세 연구를 알지 못하지만, 이전 보고에서는 마우스 알부민의 음이온성 변이체가 근위 세관 가로세포흐름을 겪을 수 있음을 보여주었습니다.<a href="#fn76" class="footnote-ref" id="fnref76" role="doc-noteref"><sup>76</sup></a> 또한 우리의 MDCK II 세포 연구는 음이온성 단백질 변이체의 비정상적인 hFcRn 재활용을 나타내지 않았습니다. 전반적으로 음이온성 단백질 제거에 대한 기전적 미지수는 각 장기 내 단백질 소실의 이질성을 강조하며 본 연구의 범위를 벗어나는 상세한 조직 특이적 연구의 필요성을 부각시킵니다.</p>
</section>
<section id="결론" class="level1">
<h1>결론</h1>
<p>표적 독립적 분포 및 제거의 시공간적 측면은 조직마다 다를 것이며, 이를 완전히 특성화하기 위해서는 세포 이질성, 장기 생리학, 특정 조직 내 단백질 이동 역학에 대한 깊은 이해와 더불어 계산 PK 모델링의 통합이 필요합니다.[^157-160] 특정 비표적 결합, 서로 다른 내피 유형에 따른 투과성, 내피 당질층의 영향, SR에 의한 인식 등 Fc 융합 단백질 및 항체 기반 치료제에 대해 다양한 가능성과 변동이 존재합니다.<a href="#fn77" class="footnote-ref" id="fnref77" role="doc-noteref"><sup>77</sup></a><a href="#fn78" class="footnote-ref" id="fnref78" role="doc-noteref"><sup>78</sup></a><a href="#fn79" class="footnote-ref" id="fnref79" role="doc-noteref"><sup>79</sup></a>[^161-165] 본 연구는 세포 비특이성과 마우스 <span class="math inline">\(\mathrm{CL}_{\mathrm{ind}}\)</span> 및 생체 분포 사이의 관계, 그리고 물리화학적 속성이 이러한 행동을 어떻게 주도할 수 있는지에 대한 통합적인 조사를 나타냅니다. Fc 단백질 소실에 대한 이해를 계속 높이기 위해서는 우리의 관찰을 바탕으로 한 추가적인 연구가 필요할 것입니다.</p>
<p>기전적 통찰과 더불어 우리의 연구는 단백질 치료제의 <span class="math inline">\(\mathrm{CL}_{\mathrm{ind}}\)</span>를 낮추기 위해 노출된 양전하를 줄이는 일반적인 전략을 뒷받침합니다. 이는 <span class="math inline">\(\mathrm{CL}_{\mathrm{ind}}\)</span> 감소를 위한 최소한의 엔지니어링 가능성을 부각시키지만<a href="#fn80" class="footnote-ref" id="fnref80" role="doc-noteref"><sup>80</sup></a><a href="#fn81" class="footnote-ref" id="fnref81" role="doc-noteref"><sup>81</sup></a>, 표적 항원 상호작용을 보존해야 할 뿐만 아니라 전하 조절의 정도를 제한해야 할 필요성도 수반합니다. 고도로 음이온성인 Fc 융합 단백질의 마우스 CL 및 조직 축적 증가 기전을 완벽히 설명하지는 못했음에도 불구하고, 우리는 소실에 해로운 영향을 미치는 음전하 임계값이 존재한다는 정보를 제공했습니다.<a href="#fn82" class="footnote-ref" id="fnref82" role="doc-noteref"><sup>82</sup></a><a href="#fn83" class="footnote-ref" id="fnref83" role="doc-noteref"><sup>83</sup></a> 따라서 다른 제조 가능성 고려 사항과 별개로 PK 관점에서 과도한 양전하 패치를 완화하기 위한 설계는 무조건적인 전하 감소만을 목표로 해서는 안 됩니다. 오히려 특정 지역의 돌연변이가 세포 처리 및 소실을 어떻게 변화시킬지에 대한 정교한 이해가 필요합니다. 보다 예측력 있는 인 비트로-인 비보 관계를 얻기 위해 개선된 물리화학적 기술자를 식별하는 것은 엄청난 이점이 될 것입니다. 단백질 치료제 소실에 대한 이해를 지속적으로 높이는 과정은 문제 소지가 있는 표면 핫스팟(hotspots)을 더 잘 매핑하거나 심지어 비정상적인 물리화학적 특성을 데 노보로 예측할 수 있는 혁신적인 약리학적 전략 및 계산 도구의 지속적인 개발과 병행되어야 합니다.[^166-167]</p>
</section>
<section id="관련-콘텐츠" class="level1">
<h1>관련 콘텐츠</h1>
<section id="지원-정보" class="level2">
<h2 class="anchored" data-anchor-id="지원-정보">지원 정보</h2>
<p>지원 정보는 https://pubs.acs.org/doi/10.1021/acs.molpharma-uct.5c01228 에서 무료로 이용할 수 있다.</p>
<p>모든 Fc 융합 단백질에 대한 분석 결과; 마우스 제거율과 인 실리코 및 인 비트로 파라미터 간의 스피어만 상관관계 결과; 전체 Fc 융합 단백질 패널의 모든 물리화학적 기술자 값; 본 연구에서 사용된 각 물리화학적 기술자의 정의; TH1 전하 하위 시리즈에 대한 MVN 유무에 따른 비이동 분율 계산 비교; Fc 융합 단백질 분자량에 따른 제거율 또는 혈청 노출 차이 부재, 그리고 Fc 융합 스캐폴드 내에서의 pI_seq 및 patch_pos_%와 마우스 제거율 간의 상관관계; 본 연구에서 분석된 모든 단백질의 CHO-K1 NSE 값, 스캐폴드 내에서의 CHO-K1 NSE와 마우스 제거율 간의 상관관계, pH 7.4 및 pH 5.8에서 측정된 CHO-K1 NSE 간의 관계; 모든 Fc 융합 단백질에 사용된 어떠한 소수성 기술자와도 pH 7.4에서의 CHO-K1 NSE 사이의 관찰 가능한 관계가 없음을 입증; pH 7.4에서의 CHO-K1 NSE와 pI_seq 및 patch_pos % 사이의 강력한 스캐폴드 내 상관관계 확립; TH1 및 LCB1 하위 시리즈의 FREM 점수 계산에 사용된 모든 MDCK 세포 분석 결과; DL650 또는 FITC 접합 후 TH1 하위 시리즈의 icIEF 크로마토그램; 세포 유무에 따른 3D 미세 생리학 시스템에서의 TH1 하위 시리즈의 간질 거동 등 (PDF)</p>
<ul>
<li>Fc 융합 단백질의 분석 요약 (XLSX)</li>
<li>스피어만 상관관계 매트릭스 및 해당 p 값 (XLSX)</li>
<li>Fc 융합 패널의 물리화학적 기술자 (XLSX)</li>
<li>물리화학적 기술자의 정의 (XLSX)</li>
<li>MVN 존재 여부에 따른 단백질의 비이동 분율 (XLSX)</li>
</ul>
</section>
</section>
<section id="참고-문헌" class="level1">
<h1>참고 문헌</h1>
<hr>
</section>
<section id="지원-정보-1" class="level1">
<h1>지원 정보</h1>
<section id="지원-표-1.-fc-융합-단백질의-분석-요약" class="level2">
<h2 class="anchored" data-anchor-id="지원-표-1.-fc-융합-단백질의-분석-요약">지원 표 1. Fc 융합 단백질의 분석 요약</h2>
<p>“aSEC MP %”와 “MCE MP %”는 각각 비환원 조건 하에서 분석용 SEC 및 MCE를 통한 메인 피크의 백분율을 나타냅니다. 두 열 모두 최대값 <span class="math inline">\(100\%\)</span> 는 녹색, 중간값 <span class="math inline">\(90\%\)</span> 는 노란색, 최소값 <span class="math inline">\(80\%\)</span> 이하는 빨간색의 3색 스케일로 표시되었습니다. “MS Relative Intensity <span class="math inline">\(\%\)</span>”는 예상 질량과 일치하는 메인 MS 피크 강도의 백분율을 나타냅니다. 이 열은 최대값 <span class="math inline">\(100\%\)</span> 는 녹색, 중간값 <span class="math inline">\(85\%\)</span> 는 노란색, 최소값 <span class="math inline">\(70\%\)</span> 이하는 빨간색의 3색 스케일로 표시되었습니다. 메인 MS 피크 강도가 약 <span class="math inline">\(80\%\)</span> 인 단백질에 대해 절단(clipping)이 감지되었습니다.</p>
</section>
<section id="지원-표-2.-마우스-제거율-대비-인-실리코-및-인-비트로-파라미터의-스피어만-상관관계-매트릭스-및-해당-p-값" class="level2">
<h2 class="anchored" data-anchor-id="지원-표-2.-마우스-제거율-대비-인-실리코-및-인-비트로-파라미터의-스피어만-상관관계-매트릭스-및-해당-p-값">지원 표 2. 마우스 제거율 대비 인 실리코 및 인 비트로 파라미터의 스피어만 상관관계 매트릭스 및 해당 p 값</h2>
<p>지원 표 3: 본 연구에서 생성된 Fc 융합 단백질의 물리화학적 기술자. 모든 약어는 지원 표 4에 정의되어 있음</p>
<p>지원 표 4: 물리화학적 기술자의 정의</p>
<p>지원 표 5: 미세 혈관 네트워크(MVN) 존재 여부에 따른 단백질의 비이동 분율</p>
<ol type="A">
<li><p><img src="images/8474fec573fde864108a61b99d78e69861d84a1fc351a1e0cb404328714975b4.jpg" class="img-fluid"><br>
<img src="images/f16df089f7c254cf9c854c888627e9ef9f36cd3c5b1014a186b2b8136a623381.jpg" class="img-fluid"></p></li>
<li><p><img src="images/5b29e37e44a4fa327eb4962e2914295a4825d59d7c7d6850d0528c0d8cea80e6.jpg" class="img-fluid"><br>
<img src="images/3a3d9055bcb61bd865ac1fe6db6b3bdd5a32a350f504ecd8d2f515388b91009a.jpg" class="img-fluid"> <img src="images/a9abc433a5240aca6055a0f52b0eaae4153084bcf2c48d2781ce47e010ac1634.jpg" class="img-fluid"> <img src="images/dc8eae60233146b90de75386f8cec9c719f4f399896dff74618523567a85bd78.jpg" class="img-fluid"> <img src="images/5157be0e6ccc359d4c94ab31e060501bd638d19d441cfc1b2a19491b8b1324f2.jpg" class="img-fluid"></p></li>
<li><p><img src="images/6b9c287645ba80e4fd560e56d973c3ee0ac89d892c2dc78a0170bcea79b5fe21.jpg" class="img-fluid"><br>
<img src="images/e4d73f8cdf750c38371b45b70e2516f40def8ffbe7641ae98fbce29407f5f111.jpg" class="img-fluid"> <img src="images/38ffe92a3982211bff25bc916ac2fb69177d4e670ce3b9a7dd4f14f02d6c1fc3.jpg" class="img-fluid"> <img src="images/02e4ab768bb9a9bcab54dd06bbdaf35b1d8e39efe1b956c5f138faa3bfc74585.jpg" class="img-fluid"> <img src="images/d924857017c95ba0d106a7cf2bf3846fbd32fb4045f64bfb67e99c7c1177002e.jpg" class="img-fluid"></p></li>
</ol>
<p>지원 그림 1: 전하 기술자와 마우스 제거율 사이의 관계. (A) 다양한 분자량의 단백질과 제거율 또는 AUC를 통해 정량화된 혈청 노출 사이에는 유의미한 차이가 측정되지 않았습니다(Dunn의 다중 비교를 포함한 Kruskal-Wallis 테스트 후 ns, 유의성 없음). (B, C) 서로 다른 Fc 융합 모달리티에 걸친 마우스 제거율과 (B) pI_seq 또는 (C) patch_pos_% 사이의 개별 관계.</p>
<ol type="A">
<li><img src="images/2a01ba356251c1e3a22ffe3cd09b9c9be12cc7e8938199977bc4a2c43162a7ab.jpg" class="img-fluid"></li>
</ol>
<p>농도: 600 nM 시간: 60 min</p>
<ol start="2" type="A">
<li><p><img src="images/c45861a42f63e4743e0d454fc930413be278e8022fd96f97567797b3db52b5a7.jpg" class="img-fluid"></p></li>
<li><p><img src="images/7a621efa523053de0fe6153c6b1831d6faada80ec83d9d2befb45fe8981354f8.jpg" class="img-fluid"><br>
<img src="images/e7bb32ac9cfe1559a265d5d46e54096cbcefd25fccd171c65fa72c3ddcdac319.jpg" class="img-fluid"></p></li>
<li><p><img src="images/f78bb65971209b2fe6395931dc3aa0ff6225d42b62759846610a3b68a186fe67.jpg" class="img-fluid"><br>
<img src="images/4800451f652efa7fa297147110d19c903db8b051bb647bc3836f4b8b36a39a17.jpg" class="img-fluid"> <img src="images/25a2393bdda679e1a190995fe600fed0259f141a7724961281dce36c52288e83.jpg" class="img-fluid"> <img src="images/b7aef9b74c221568061d29b5b3757a982661164c78a97ca0590194f8de65f0e3.jpg" class="img-fluid"></p></li>
<li><p><img src="images/5054faac576809a6aca0b9c6f27cfbc74b0f34575760f8dd06c342dfdaf5faf1.jpg" class="img-fluid"></p></li>
</ol>
</section>
<section id="지원-그림-2-cho-k1-세포내섭취는-테스트된-모든-단백질-모달리티에서-ph-의존적이다." class="level2">
<h2 class="anchored" data-anchor-id="지원-그림-2-cho-k1-세포내섭취는-테스트된-모든-단백질-모달리티에서-ph-의존적이다.">지원 그림 2: CHO-K1 세포내섭취는 테스트된 모든 단백질 모달리티에서 pH 의존적이다.</h2>
<ol type="A">
<li>본 연구에서 설명된 생성된 Fc 융합 단백질, (B) 상세 조사를 위해 사용된 LCB1 및 TH1 하위 시리즈, (C) 개별 Fc 융합 스캐폴드, 그리고 (D) <a href="#fn84" class="footnote-ref" id="fnref84" role="doc-noteref"><sup>84</sup></a><a href="#fn85" class="footnote-ref" id="fnref85" role="doc-noteref"><sup>85</sup></a>에서 이전에 평가된 일련의 단일클론 항체에 대한 pH 5.8 및 7.4에서의 개별 CHO-K1 비특이적 세포내섭취(NSE) 값. (E) 거의 모든 단백질이 pH 5.8 에서 더 높은 NSE를 나타냈으며, 이는 pH 7.4 에서의 해당 NSE 값과 강하게 상관관계가 있었습니다(스피어만 <span class="math inline">\(r = 0.93, p &lt; 0.0001\)</span>).</li>
</ol>
<p><img src="images/f5f57338897fc6958a16a841a7faabfafdac9b36775baa270a6d3bb6e94b7f80.jpg" class="img-fluid"> <img src="images/9bb868c418c156af681eae2d6d3fd677451512aaffbf7e2480506cdc5bc629ed.jpg" class="img-fluid"> <img src="images/9061a0319dc0654c93895d49fedcb780b686420db834b87a3e9d059acd224dd0.jpg" class="img-fluid"> <img src="images/3849dd00770cbe7c850da932ea5d542084d9d57241f67b5fdd1c8ba614daf760.jpg" class="img-fluid"> <img src="images/885389eb5250ab1005d21a59125841cd9ecc58a868a505ac8a86452801bc33f3.jpg" class="img-fluid"> <img src="images/bf36cea274428caa4c49b3fb37db785e22837b6ba1e7362aa2b2893e3ad12ac9.jpg" class="img-fluid"> <img src="images/45bf1fd20c0812a41f1704eb9461ed146152c82bdb43ef20613529d9843638ac.jpg" class="img-fluid"> <img src="images/a322c5354ba628429bbd1f3a514935654982d634b50061fe16cc4aecae9b1b90.jpg" class="img-fluid"></p>
<p>지원 그림 3: CHO-K1 세포의 비특이적 세포내섭취와 어떠한 소수성 기술자 사이에서도 관계가 관찰되지 않음.</p>
<ol start="2" type="A">
<li><p><img src="images/366402151fd0014da131db4539710e1eb48df3775e88846215a446a4d59fda78.jpg" class="img-fluid"><br>
<img src="images/853ad0e93aeafe335a54d39fc72b18c5c7b7b9c685bc4514ad83ae9ba56810b2.jpg" class="img-fluid"> <img src="images/e78e873e4fc0bc1652025e6ff0289ef73de4b0a50a16836864f9b2b382e602de.jpg" class="img-fluid"> <img src="images/aa8ebea08753e6a766a3d1640e91d25c98347842045d0a08d18ced080900cc1a.jpg" class="img-fluid"> <img src="images/d05417b683fa2bfdb3cf2f45de6f5ec7fd0faf140a696373ea2c2e33523ce31f.jpg" class="img-fluid"></p></li>
<li><p><img src="images/4dd4c579b5c23b4968493a6fcaf11215618d4e4b12c9bdbfcbd343c899c1f5a8.jpg" class="img-fluid"><br>
<img src="images/7284a8cd9c8fd771bcb22093c083c2c82b6a82beb585cd16c68e818e890b6acb.jpg" class="img-fluid"> <img src="images/6207498fa9b8ae470383688f1b3d00bb0376bb63f8dd918283cd820904ecf752.jpg" class="img-fluid"> <img src="images/53670a42a5ee23dea60e4e09a501a008e03c0525e23a57387a3a088b38bff134.jpg" class="img-fluid"> <img src="images/1eb0d41df85fa9890256aef995f194ccd8b43e8184146100e5f1c04cc3d596a5.jpg" class="img-fluid"></p></li>
</ol>
<p>지원 그림 4: Fc 융합 모달리티 내에서는 전하 기술자와 비특이적 세포내섭취 사이의 높은 상관관계가 관찰되지만, 단일클론 항체 패널과 함께 평가할 때는 그렇지 않음. (A) 모든 Fc 융합 단백질 및 항체의 전체 아미노산 서열로부터 알짜 전하를 계산했습니다. 이는 실험 방법에 설명된 대로 이가 Fc 융합 구조의 일가 단백질을 사용하여 얻은 본 보고서 전체의 Fc 융합 알짜 전하 파라미터와는 다릅니다. 모든 모달리티를 동시에 검사할 때 유의미한 스피어만 상관관계는 관찰되지 않았습니다(스피어만 <span class="math inline">\(r = 0.23, ns\)</span>). 서열 기반 pI(B) 또는 (C) 계산된 양성 단백질 패치의 총 표면적 백분율(patch_pos_ <span class="math inline">\(\%\)</span> ) 대 CHO-K1 세포 내의 비특이적 세포내섭취 양의 플롯은 강한 관계를 나타냈습니다.</p>
<ol type="A">
<li><p><img src="images/68c509615fcf6e369ebc4c4bcfeac58072201f0917d54b420dde056b9227644a.jpg" class="img-fluid"></p></li>
<li><p><img src="images/3ffa5b7c45947cf8bf0d4d3f01d13a7db119da4dcfbea71a5e7baf30f28886cf.jpg" class="img-fluid"></p></li>
</ol>
<p>C<br>
<img src="images/f0f7b4d0a366146a3ec58042187ba73ee480a80528ed7248b6d96dafed4e07a6.jpg" class="img-fluid"></p>
<p>D <img src="images/095ebb53f64c1bc912f7179419c0c73c8bf6ec16965fab628b7c99210a081531.jpg" class="img-fluid"></p>
<p>E <img src="images/088c37aab08951db26df21355cb9896daa07b6d59707ba97951297276b41b6a8.jpg" class="img-fluid"></p>
<ol start="6" type="A">
<li><p><img src="images/8a8d0558417a3bf40aa4e61fa5054df504f118fb8f1e44f8c0e428e99fe369f2.jpg" class="img-fluid"></p></li>
<li><p><img src="images/abbd4258cf949847eaab18ee2adb89d0cbe7fc962c1d9e277b18c05adbc534db.jpg" class="img-fluid"></p></li>
<li><p><img src="images/a4195e79158d170ffbdd79cd3c39bf9b2f853b13bfbb84819a5ff0ccf50c4cdc.jpg" class="img-fluid"></p></li>
<li><p><img src="images/ddbc23fba442212ac62033c23a16ad52c3f6003676970d44143dd0277ea7edf1.jpg" class="img-fluid"></p></li>
</ol>
<p>지원 그림 5: 비특이적 행동은 세포 분석 내에서 인간 FcRn 재활용에 상당한 영향을 미친다. (A) 실험 방법에 설명된 대로 약간의 실험적 수정을 가하여 사용된 세포 분석의 모식도. FcRn 발현(B-D) 또는 모세포 MDCK II 세포(E-G)에서의 테스트 단백질에 대한 섭취, 재활용 및 잔류 결과. 각 단백질에 대한 재활용 효율(H) 및 비특이적 섭취 계수 점수(I)는 최종 FcRn 재활용 효율 지표 값을 계산하는 데 사용됩니다.</p>
<p><img src="images/00a06dd727aa5a3225b4ec166d12e342558f32f0aec5b455cd81db9e459ded10.jpg" class="img-fluid"> <img src="images/c3293df5b8cd8a6da6eb8ae0fb666d3116ca1fcd6fb0b1534c5953fcb85ac95e.jpg" class="img-fluid"> <img src="images/7767af7e4b07317e13908922e62bb2e897812bd5bf23a4722642c760452297cc.jpg" class="img-fluid"> <img src="images/8bdfcda3067c576937619f2b5ddc62a8c3911a3e3e6a379874bae98aadc09800.jpg" class="img-fluid"></p>
<p>지원 그림 6: 형광 접합 후 등전점(pI) 변화를 정량화하기 위한 이미지화된 모세관 등전점 전기영동(icIEF). (A) TH1 전하 시리즈를 Dylight 650(DL650)으로 1X 비율로 표지하고 icIEF를 수행했습니다. 묘사된 크로마토그램은 염기성 TH1 단백질의 경우 1 단위를 초과하는 pI 이동을 보여줍니다. 이러한 이유로, 염기성 TH1 단백질만 더 낮은 형광체 농도(0.5 X)로 DL650으로 다시 표지되었습니다. (B) 0.5X DL650 염기성 TH1 및 플루오레세인(FITC)으로 표지된 모든 TH1 전하 변이체 분석.</p>
<ol type="A">
<li><p><img src="images/6d19588dc94835d475d18e355ea42a1799f305b072989bfcc3690b9c283ca9dc.jpg" class="img-fluid"></p></li>
<li><p><img src="images/32daf88eda4f4923657e5752e90a93680a7f7b26705e613dca758f04a01c267a.jpg" class="img-fluid"></p></li>
</ol>
<p>지원 그림 7: 미세 혈관 네트워크(MVN)의 존재는 간질 확산 행동에 영향을 미칩니다. (A) MVN이 없는 미세 유체 장치에서 실행된 분석 물질의 광퇴색 후 형광 회복(FRAP) 곡선 플롯. (B) MVN이 있거나 없는 FRAP 연구에서 얻은 확산성 측정치.</p>


</section>
</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>Bryniarski, M. A.; Tuhin, M. T. H.; Shomin, C. D.; Nasrollahi, F.; Ko, E. C.; Soto, M.; et al.&nbsp;Utility of Cellular Measurements of Non-Specific Endocytosis to Assess the Target-Independent Clearance of Monoclonal Antibodies. <em>J. Pharm. Sci.</em> <strong>2024</strong>, <em>113</em>, 3100.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>Rocklin, G. J.; Chidyausiku, T. M.; Goreshnik, I.; Ford, A.; Houliston, S.; Lemak, A.; et al.&nbsp;Global analysis of protein folding using massively parallel design, synthesis, and testing. <em>Science</em> <strong>2017</strong>, <em>357</em>, 168-175.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>Koga, N.; Tatsumi-Koga, R.; Liu, G.; Xiao, R.; Acton, T. B.; Montelione, G. T.; Baker, D. Principles for designing ideal protein structures. <em>Nature</em> <strong>2012</strong>, <em>491</em>, 222-227.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>Huang, P. S.; Feldmeier, K.; Parmeggiani, F.; Fernandez Velasco, D. A.; Hocker, B.; Baker, D. De novo design of a four-fold symmetric TIM-barrel protein with atomic-level accuracy. <em>Nat. Chem. Biol.</em> <strong>2016</strong>, <em>12</em>, 29-34.<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p>Cao, L.; Goreshnik, I.; Coventry, B.; Case, J. B.; Miller, L.; Kozodoy, L.; et al.&nbsp;De novo design of picomolar SARS-CoV-2 miniprotein inhibitors. <em>Science</em> <strong>2020</strong>, <em>370</em>, 426-431.<a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn6"><p>Huddy, T. F.; Hsia, Y.; Kibler, R. D.; Xu, J.; Bethel, N.; Nagarajan, D.; et al.&nbsp;Blueprinting extendable nanomaterials with standardized protein blocks. <em>Nature</em> <strong>2024</strong>, <em>627</em>, 898-904.<a href="#fnref6" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn7"><p>Estes, B.; Sudom, A.; Gong, D.; Whittington, D. A.; Li, V.; Mohr, C.; et al.&nbsp;Next generation Fc scaffold for multispecific antibodies. <em>iScience</em> <strong>2021</strong>, <em>24</em>, 103447.<a href="#fnref7" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn8"><p>Sun, H.; Wang, S.; Lu, M.; Tinberg, C. E.; Alba, B. M. Protein production from HEK293 cell line-derived stable pools with high protein quality and quantity to support discovery research. <em>PLoS One</em> <strong>2023</strong>, <em>18</em>, No.&nbsp;e0285971.<a href="#fnref8" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn9"><p>Sun, H.; Wang, S.; Lu, M.; Tinberg, C. E.; Alba, B. M. Protein production from HEK293 cell line-derived stable pools with high protein quality and quantity to support discovery research. <em>PLoS One</em> <strong>2023</strong>, <em>18</em>, No.&nbsp;e0285971.<a href="#fnref9" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn10"><p>Triguero, D.; Buciak, J. L.; Pardridge, W. M. Cationization of immunoglobulin G results in enhanced organ uptake of the protein after intravenous administration in rats and primate. <em>J. Pharmacol. Exp. Ther.</em> <strong>1991</strong>, <em>258</em>, 186-192.<a href="#fnref10" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn11"><p>van Rooijen, N.; Hendrikx, E. Liposomes for Specific Depletion of Macrophages from Organs and Tissues. <em>Mol. Biol.</em> <strong>2010</strong>, <em>605</em>, 189-203.<a href="#fnref11" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn12"><p>Bryniarski, M. A.; Tuhin, M. T. H.; Acker, T. M.; Wakefield, D. L.; Sethaputra, P. G.; Cook, K. D.; et al.&nbsp;Cellular Neonatal Fc Receptor Recycling Efficiencies can Differentiate Target-Independent Clearance Mechanisms of Monoclonal Antibodies. <em>J. Pharm. Sci.</em> <strong>2024</strong>, <em>113</em>, 2879–2894.<a href="#fnref12" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn13"><p>Grevys, A.; Nilsen, J.; Sand, K. M. K.; Daba, M. B.; Oynebraten, I.; Bern, M.; et al.&nbsp;A human endothelial cell-based recycling assay for screening of FcRn targeted molecules. <em>Nat. Commun.</em> <strong>2018</strong>, <em>9</em>, 621.<a href="#fnref13" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn14"><p>Hajal, C.; Offeddu, G. S.; Shin, Y.; Zhang, S.; Morozova, O.; Hickman, D.; et al.&nbsp;Engineered human blood-brain barrier microfluidic model for vascular permeability analyses. <em>Nat. Protoc.</em> <strong>2022</strong>, <em>17</em>, 95-128.<a href="#fnref14" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn15"><p>Offeddu, G. S.; Serrano, J. C.; Wan, Z.; Bryniarski, M. A.; Humphreys, S. C.; Chen, S. W.; et al.&nbsp;Microphysiological endothelial models to characterize subcutaneous drug absorption. <em>ALTEX</em> <strong>2023</strong>, <em>40</em>, 299-313.<a href="#fnref15" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn16"><p>Offeddu, G. S.; Haase, K.; Gillrie, M. R.; Li, R.; Morozova, O.; Hickman, D.; et al.&nbsp;An on-chip model of protein paracellular and transcellular permeability in the microcirculation. <em>Biomaterials</em> <strong>2019</strong>, <em>212</em>, 115-125.<a href="#fnref16" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn17"><p>Rocklin, G. J.; Chidyausiku, T. M.; Goreshnik, I.; Ford, A.; Houliston, S.; Lemak, A.; et al.&nbsp;Global analysis of protein folding using massively parallel design, synthesis, and testing. <em>Science</em> <strong>2017</strong>, <em>357</em>, 168-175.<a href="#fnref17" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn18"><p>Cao, L.; Goreshnik, I.; Coventry, B.; Case, J. B.; Miller, L.; Kozodoy, L.; et al.&nbsp;De novo design of picomolar SARS-CoV-2 miniprotein inhibitors. <em>Science</em> <strong>2020</strong>, <em>370</em>, 426-431.<a href="#fnref18" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn19"><p>Koga, N.; Tatsumi-Koga, R.; Liu, G.; Xiao, R.; Acton, T. B.; Montelione, G. T.; Baker, D. Principles for designing ideal protein structures. <em>Nature</em> <strong>2012</strong>, <em>491</em>, 222-227.<a href="#fnref19" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn20"><p>Huang, P. S.; Feldmeier, K.; Parmeggiani, F.; Fernandez Velasco, D. A.; Hocker, B.; Baker, D. De novo design of a four-fold symmetric TIM-barrel protein with atomic-level accuracy. <em>Nat. Chem. Biol.</em> <strong>2016</strong>, <em>12</em>, 29-34.<a href="#fnref20" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn21"><p>Estes, B.; Sudom, A.; Gong, D.; Whittington, D. A.; Li, V.; Mohr, C.; et al.&nbsp;Next generation Fc scaffold for multispecific antibodies. <em>iScience</em> <strong>2021</strong>, <em>24</em>, 103447.<a href="#fnref21" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn22"><p>Liu, L.; Jacobsen, F. W.; Everds, N.; Zhuang, Y.; Yu, Y. B.; Li, N.; et al.&nbsp;Biological Characterization of a Stable Effector Functionless (SEFL) Monoclonal Antibody Scaffold in Vitro. <em>J. Biol. Chem.</em> <strong>2017</strong>, <em>292</em>, 1876-1883.<a href="#fnref22" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn23"><p>Boswell, C. A.; Tesar, D. B.; Mukhyala, K.; Theil, F. P.; Fielder, P. J.; Khawli, L. A. Effects of charge on antibody tissue distribution and pharmacokinetics. <em>Bioconjug. Chem.</em> <strong>2010</strong>, <em>21</em>, 2153-2163.<a href="#fnref23" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn24"><p>Liu, S.; Verma, A.; Kettenberger, H.; Richter, W. F.; Shah, D. K. Effect of variable domain charge on in vitro and in vivo disposition of monoclonal antibodies. <em>MAbs</em> <strong>2021</strong>, <em>13</em>, 1993769.<a href="#fnref24" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn25"><p>Bryniarski, M. A.; Tuhin, M. T. H.; Shomin, C. D.; Nasrollahi, F.; Ko, E. C.; Soto, M.; et al.&nbsp;Utility of Cellular Measurements of Non-Specific Endocytosis to Assess the Target-Independent Clearance of Monoclonal Antibodies. <em>J. Pharm. Sci.</em> <strong>2024</strong>, <em>113</em>, 3100.<a href="#fnref25" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn26"><p>Stüber, J. C.; Rechberger, K. F.; Miladinović, S. M.; Pöschinger, T.; Zimmermann, T.; Villenave, R.; et al.&nbsp;Impact of charge patches on tumor disposition and biodistribution of therapeutic antibodies. <em>AAPS Open</em> <strong>2022</strong>, <em>8</em>, 3.<a href="#fnref26" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn27"><p>Bryniarski, M. A.; Tuhin, M. T. H.; Acker, T. M.; Wakefield, D. L.; Sethaputra, P. G.; Cook, K. D.; et al.&nbsp;Cellular Neonatal Fc Receptor Recycling Efficiencies can Differentiate Target-Independent Clearance Mechanisms of Monoclonal Antibodies. <em>J. Pharm. Sci.</em> <strong>2024</strong>, <em>113</em>, 2879–2894.<a href="#fnref27" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn28"><p>Bryniarski, M. A.; Tuhin, M. T. H.; Acker, T. M.; Wakefield, D. L.; Sethaputra, P. G.; Cook, K. D.; et al.&nbsp;Cellular Neonatal Fc Receptor Recycling Efficiencies can Differentiate Target-Independent Clearance Mechanisms of Monoclonal Antibodies. <em>J. Pharm. Sci.</em> <strong>2024</strong>, <em>113</em>, 2879–2894.<a href="#fnref28" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn29"><p>Bryniarski, M. A.; Tuhin, M. T. H.; Acker, T. M.; Wakefield, D. L.; Sethaputra, P. G.; Cook, K. D.; et al.&nbsp;Cellular Neonatal Fc Receptor Recycling Efficiencies can Differentiate Target-Independent Clearance Mechanisms of Monoclonal Antibodies. <em>J. Pharm. Sci.</em> <strong>2024</strong>, <em>113</em>, 2879–2894.<a href="#fnref29" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn30"><p>Bryniarski, M. A.; Tuhin, M. T. H.; Shomin, C. D.; Nasrollahi, F.; Ko, E. C.; Soto, M.; et al.&nbsp;Utility of Cellular Measurements of Non-Specific Endocytosis to Assess the Target-Independent Clearance of Monoclonal Antibodies. <em>J. Pharm. Sci.</em> <strong>2024</strong>, <em>113</em>, 3100.<a href="#fnref30" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn31"><p>Bryniarski, M. A.; Tuhin, M. T. H.; Acker, T. M.; Wakefield, D. L.; Sethaputra, P. G.; Cook, K. D.; et al.&nbsp;Cellular Neonatal Fc Receptor Recycling Efficiencies can Differentiate Target-Independent Clearance Mechanisms of Monoclonal Antibodies. <em>J. Pharm. Sci.</em> <strong>2024</strong>, <em>113</em>, 2879–2894.<a href="#fnref31" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn32"><p>Bryniarski, M. A.; Tuhin, M. T. H.; Acker, T. M.; Wakefield, D. L.; Sethaputra, P. G.; Cook, K. D.; et al.&nbsp;Cellular Neonatal Fc Receptor Recycling Efficiencies can Differentiate Target-Independent Clearance Mechanisms of Monoclonal Antibodies. <em>J. Pharm. Sci.</em> <strong>2024</strong>, <em>113</em>, 2879–2894.<a href="#fnref32" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn33"><p>Ausserwoger, H.; Schneider, M. M.; Herling, T. W.; Arosio, P.; Invernizzi, G.; Knowles, T. P. J.; Lorenzen, N. Non-specificity as the sticky problem in therapeutic antibody development. <em>Nat. Rev.&nbsp;Chem.</em> <strong>2022</strong>, <em>6</em>, 844-861.<a href="#fnref33" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn34"><p>Bryniarski, M. A.; Tuhin, M. T. H.; Shomin, C. D.; Nasrollahi, F.; Ko, E. C.; Soto, M.; et al.&nbsp;Utility of Cellular Measurements of Non-Specific Endocytosis to Assess the Target-Independent Clearance of Monoclonal Antibodies. <em>J. Pharm. Sci.</em> <strong>2024</strong>, <em>113</em>, 3100.<a href="#fnref34" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn35"><p>Tibbitts, J.; Canter, D.; Graff, R.; Smith, A.; Khawli, L. A. Key factors influencing ADME properties of therapeutic proteins: A need for ADME characterization in drug discovery and development. <em>MAbs</em> <strong>2016</strong>, <em>8</em>, 229-245.<a href="#fnref35" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn36"><p>Wright, A.; Sato, Y.; Okada, T.; Chang, K.; Endo, T.; Morrison, S. In vivo trafficking and catabolism of IgG1 antibodies with Fc associated carbohydrates of differing structure. <em>Glycobiology</em> <strong>2000</strong>, <em>10</em>, 1347-1355.<a href="#fnref36" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn37"><p>Aird, W. C. Phenotypic heterogeneity of the endothelium: I. Structure, function, and mechanisms. <em>Circ. Res.</em> <strong>2007</strong>, <em>100</em>, 158-173.<a href="#fnref37" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn38"><p>Ono, S.; Egawa, G.; Kabashima, K. Regulation of blood vascular permeability in the skin. <em>Regen</em> <strong>2017</strong>, <em>37</em>, 11.<a href="#fnref38" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn39"><p>Aird, W. C. Phenotypic heterogeneity of the endothelium: I. Structure, function, and mechanisms. <em>Circ. Res.</em> <strong>2007</strong>, <em>100</em>, 158-173.<a href="#fnref39" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn40"><p>Mehta, D.; Malik, A. B. Signaling mechanisms regulating endothelial permeability. <em>Physiol. Rev.</em> <strong>2006</strong>, <em>86</em>, 279-367.<a href="#fnref40" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn41"><p>Aird, W. C. Phenotypic heterogeneity of the endothelium: I. Structure, function, and mechanisms. <em>Circ. Res.</em> <strong>2007</strong>, <em>100</em>, 158-173.<a href="#fnref41" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn42"><p>Offeddu, G. S.; Haase, K.; Gillrie, M. R.; Li, R.; Morozova, O.; Hickman, D.; et al.&nbsp;An on-chip model of protein paracellular and transcellular permeability in the microcirculation. <em>Biomaterials</em> <strong>2019</strong>, <em>212</em>, 115-125.<a href="#fnref42" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn43"><p>Boswell, C. A.; Tesar, D. B.; Mukhyala, K.; Theil, F. P.; Fielder, P. J.; Khawli, L. A. Effects of charge on antibody tissue distribution and pharmacokinetics. <em>Bioconjug. Chem.</em> <strong>2010</strong>, <em>21</em>, 2153-2163.<a href="#fnref43" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn44"><p>Tibbitts, J.; Canter, D.; Graff, R.; Smith, A.; Khawli, L. A. Key factors influencing ADME properties of therapeutic proteins: A need for ADME characterization in drug discovery and development. <em>MAbs</em> <strong>2016</strong>, <em>8</em>, 229-245.<a href="#fnref44" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn45"><p>Boswell, C. A.; Tesar, D. B.; Mukhyala, K.; Theil, F. P.; Fielder, P. J.; Khawli, L. A. Effects of charge on antibody tissue distribution and pharmacokinetics. <em>Bioconjug. Chem.</em> <strong>2010</strong>, <em>21</em>, 2153-2163.<a href="#fnref45" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn46"><p>Offeddu, G. S.; Haase, K.; Gillrie, M. R.; Li, R.; Morozova, O.; Hickman, D.; et al.&nbsp;An on-chip model of protein paracellular and transcellular permeability in the microcirculation. <em>Biomaterials</em> <strong>2019</strong>, <em>212</em>, 115-125.<a href="#fnref46" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn47"><p>Offeddu, G. S.; Haase, K.; Gillrie, M. R.; Li, R.; Morozova, O.; Hickman, D.; et al.&nbsp;An on-chip model of protein paracellular and transcellular permeability in the microcirculation. <em>Biomaterials</em> <strong>2019</strong>, <em>212</em>, 115-125.<a href="#fnref47" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn48"><p>Offeddu, G. S.; Haase, K.; Gillrie, M. R.; Li, R.; Morozova, O.; Hickman, D.; et al.&nbsp;An on-chip model of protein paracellular and transcellular permeability in the microcirculation. <em>Biomaterials</em> <strong>2019</strong>, <em>212</em>, 115-125.<a href="#fnref48" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn49"><p>Steinman, R. M.; Mellman, I. S.; Muller, W. A.; Cohn, Z. A. Endocytosis and the recycling of plasma membrane. <em>J. Cell Biol.</em> <strong>1983</strong>, <em>96</em>, 1-27.<a href="#fnref49" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn50"><p>Steinman, R. M.; Brodie, S. E.; Cohn, Z. A. Membrane flow during pinocytosis. A stereologic analysis. <em>J. Cell Biol.</em> <strong>1976</strong>, <em>68</em>, 665-687.<a href="#fnref50" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn51"><p>van Rooijen, N.; Hendrikx, E. Liposomes for Specific Depletion of Macrophages from Organs and Tissues. <em>Mol. Biol.</em> <strong>2010</strong>, <em>605</em>, 189-203.<a href="#fnref51" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn52"><p>Rooijen, N. V.; Sanders, A. Liposome mediated depletion of macrophages: mechanism of action, preparation of liposomes and applications. <em>J. Immunol. Methods</em> <strong>1994</strong>, <em>174</em>, 83-93.<a href="#fnref52" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn53"><p>Emonts, J.; Buyel, J. F. An overview of descriptors to capture protein properties - Tools and perspectives in the context of QSAR modeling. <em>Comput. Struct. Biotechnol. J.</em> <strong>2023</strong>, <em>21</em>, 3234-3247.<a href="#fnref53" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn54"><p>Ward, E. S.; Ober, R. J. Commentary: “There’s been a Flaw in Our Thinking”. <em>Front. Immunol.</em> <strong>2015</strong>, <em>6</em>, 351.<a href="#fnref54" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn55"><p>Bryniarski, M. A.; Tuhin, M. T. H.; Shomin, C. D.; Nasrollahi, F.; Ko, E. C.; Soto, M.; et al.&nbsp;Utility of Cellular Measurements of Non-Specific Endocytosis to Assess the Target-Independent Clearance of Monoclonal Antibodies. <em>J. Pharm. Sci.</em> <strong>2024</strong>, <em>113</em>, 3100.<a href="#fnref55" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn56"><p>Ghetie, V.; Ward, E. S. Transcytosis and catabolism of antibody. <em>Immunol. Res.</em> <strong>2002</strong>, <em>25</em>, 097-114.<a href="#fnref56" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn57"><p>Jensen, P. F.; Schoch, A.; Larraillet, V.; Hilger, M.; Schlothauer, T.; Emrich, T.; Rand, K. D. A Two-pronged Binding Mechanism of IgG to the Neonatal Fc Receptor Controls Complex Stability and IgG Serum Half-life. <em>Mol. Cell. Proteomics</em> <strong>2017</strong>, <em>16</em>, 451-456.<a href="#fnref57" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn58"><p>Igawa, T.; Mimoto, F.; Hattori, K. pH-dependent antigen-binding antibodies as a novel therapeutic modality. <em>Biochim. Biophys. Acta</em> <strong>2014</strong>, <em>1844</em>, 1943-1950.<a href="#fnref58" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn59"><p>Kelly, R. L.; Sun, T.; Jain, T.; Caffry, I.; Yu, Y.; Cao, Y.; et al.&nbsp;High throughput cross-interaction measures for human IgG1 antibodies correlate with clearance rates in mice. <em>MAbs</em> <strong>2015</strong>, <em>7</em>, 770-777.<a href="#fnref59" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn60"><p>Liu, S.; Verma, A.; Kettenberger, H.; Richter, W. F.; Shah, D. K. Effect of variable domain charge on in vitro and in vivo disposition of monoclonal antibodies. <em>MAbs</em> <strong>2021</strong>, <em>13</em>, 1993769.<a href="#fnref60" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn61"><p>Shah, D. K.; Betts, A. M. Antibody biodistribution coefficients: inferring tissue concentrations of monoclonal antibodies based on the plasma concentrations in several preclinical species and human. <em>MAbs</em> <strong>2013</strong>, <em>5</em>, 297-305.<a href="#fnref61" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn62"><p>Ober, R. J.; Radu, C. G.; Ghetie, V.; Ward, E. S. Differences in promiscuity for antibody-FcRn interactions across species: implications for therapeutic antibodies. <em>Int. Immunol.</em> <strong>2001</strong>, <em>13</em>, 1551-1559.<a href="#fnref62" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn63"><p>Boswell, C. A.; Tesar, D. B.; Mukhyala, K.; Theil, F. P.; Fielder, P. J.; Khawli, L. A. Effects of charge on antibody tissue distribution and pharmacokinetics. <em>Bioconjug. Chem.</em> <strong>2010</strong>, <em>21</em>, 2153-2163.<a href="#fnref63" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn64"><p>Frantz, C.; Stewart, K. M.; Weaver, V. M. The extracellular matrix at a glance. <em>J. Cell Sci.</em> <strong>2010</strong>, <em>123</em>, 4195-4200.<a href="#fnref64" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn65"><p>Simionescu, M.; Simionescu, N. Endothelial transport of macromolecules: transcytosis and endocytosis. A look from cell biology. <em>Cell Biol. Rev.</em> <strong>1991</strong>, <em>2S</em>, 1-78.<a href="#fnref65" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn66"><p>Ghinea, N.; Hasu, M. Charge effect on binding, uptake and transport of ferritin through fenestrated endothelium. <em>J. Submicrosc. Cytol.</em> <strong>1986</strong>, <em>18</em>, 647-659.<a href="#fnref66" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn67"><p>Offeddu, G. S.; Haase, K.; Gillrie, M. R.; Li, R.; Morozova, O.; Hickman, D.; et al.&nbsp;An on-chip model of protein paracellular and transcellular permeability in the microcirculation. <em>Biomaterials</em> <strong>2019</strong>, <em>212</em>, 115-125.<a href="#fnref67" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn68"><p>Ono, S.; Egawa, G.; Nomura, T.; Kitoh, A.; Dainichi, T.; Otsuka, A.; et al.&nbsp;Abl family tyrosine kinases govern IgG extravasation in the skin in a murine pemphigus model. <em>Nat. Commun.</em> <strong>2019</strong>, <em>10</em>, 4432.<a href="#fnref68" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn69"><p>Simionescu, M.; Simionescu, N. Endothelial transport of macromolecules: transcytosis and endocytosis. A look from cell biology. <em>Cell Biol. Rev.</em> <strong>1991</strong>, <em>2S</em>, 1-78.<a href="#fnref69" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn70"><p>Schnitzer, J. E. Caveolae: from basic trafficking mechanisms to targeting transcytosis for tissue-specific drug and gene delivery in vivo. <em>Adv. Drug Deliv Rev.</em> <strong>2001</strong>, <em>49</em>, 265-280.<a href="#fnref70" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn71"><p>PrabhuDas, M. R.; Baldwin, C. L.; Bollyky, P. L.; Bowdish, D. M. E.; Drickamer, K.; Febbraio, M.; et al.&nbsp;A Consensus Definitive Classification of Scavenger Receptors and Their Roles in Health and Disease. <em>J. Immunol.</em> <strong>2017</strong>, <em>198</em>, 3775-3789.<a href="#fnref71" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn72"><p>Norden, D. M.; Navia, C. T.; Sullivan, J. T.; Doranz, B. J. The emergence of cell-based protein arrays to test for polyspecific off-target binding of antibody therapeutics. <em>MAbs</em> <strong>2024</strong>, <em>16</em>, 2393785.<a href="#fnref72" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn73"><p>Bhandari, S.; Larsen, A. K.; McCourt, P.; Smedsrod, B.; Sorensen, K. K. The Scavenger Function of Liver Sinusoidal Endothelial Cells in Health and Disease. <em>Front. Physiol.</em> <strong>2021</strong>, <em>12</em>, 757469.<a href="#fnref73" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn74"><p>Carone, F. A.; Peterson, D. R.; Oparil, S.; Pullman, T. N. Renal tubular transport and catabolism of proteins and peptides. <em>Kidney Int.</em> <strong>1979</strong>, <em>16</em>, 271-278.<a href="#fnref74" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn75"><p>Rafidi, H.; Estevez, A.; Ferl, G. Z.; Mandikian, D.; Stainton, S.; Sermeno, L.; et al.&nbsp;Imaging Reveals Importance of Shape and Flexibility for Glomerular Filtration of Biologics. <em>Mol. Cancer Ther.</em> <strong>2021</strong>, <em>20</em>, 2008-2015.<a href="#fnref75" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn76"><p>Tenten, V.; Menzel, S.; Kunter, U.; Sicking, E. M.; van Roeyen, C. R.; Sanden, S. K.; et al.&nbsp;Albumin is recycled from the primary urine by tubular transcytosis. <em>J. Am. Soc. Nephrol.</em> <strong>2013</strong>, <em>24</em>, 1966-1980.<a href="#fnref76" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn77"><p>Datta-Mannan, A. Mechanisms Influencing the Pharmacokinetics and Disposition of Monoclonal Antibodies and Peptides. <em>Drug Metab. Dispos.</em> <strong>2019</strong>, <em>47</em>, 1100-1110.<a href="#fnref77" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn78"><p>Norden, D. M.; Navia, C. T.; Sullivan, J. T.; Doranz, B. J. The emergence of cell-based protein arrays to test for polyspecific off-target binding of antibody therapeutics. <em>MAbs</em> <strong>2024</strong>, <em>16</em>, 2393785.<a href="#fnref78" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn79"><p>Conner, K. P.; Devanaboyina, S. C.; Thomas, V. A.; Rock, D. A. The biodistribution of therapeutic proteins: Mechanism, implications for pharmacokinetics, and methods of evaluation. <em>Pharmacol. Ther.</em> <strong>2020</strong>, <em>212</em>, 107574.<a href="#fnref79" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn80"><p>Datta-Mannan, A. Mechanisms Influencing the Pharmacokinetics and Disposition of Monoclonal Antibodies and Peptides. <em>Drug Metab. Dispos.</em> <strong>2019</strong>, <em>47</em>, 1100-1110.<a href="#fnref80" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn81"><p>Igawa, T.; Tsunoda, H.; Tachibana, T.; Maeda, A.; Mimoto, F.; Moriyama, C.; et al.&nbsp;Reduced elimination of IgG antibodies by engineering the variable region. <em>Protein Eng. Des. Sel.</em> <strong>2010</strong>, <em>23</em>, 385-392.<a href="#fnref81" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn82"><p>Boswell, C. A.; Tesar, D. B.; Mukhyala, K.; Theil, F. P.; Fielder, P. J.; Khawli, L. A. Effects of charge on antibody tissue distribution and pharmacokinetics. <em>Bioconjug. Chem.</em> <strong>2010</strong>, <em>21</em>, 2153-2163.<a href="#fnref82" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn83"><p>Liu, S.; Verma, A.; Kettenberger, H.; Richter, W. F.; Shah, D. K. Effect of variable domain charge on in vitro and in vivo disposition of monoclonal antibodies. <em>MAbs</em> <strong>2021</strong>, <em>13</em>, 1993769.<a href="#fnref83" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn84"><p>Keri, D.; Walker, M.; Singh, I.; Nishikawa, K.; Garces, F. Next generation of multispecific antibody engineering. <em>Anti. Ther.</em> <strong>2024</strong>, <em>7</em>, 37-52.<a href="#fnref84" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn85"><p>Lucchi, R.; Bentanachs, J.; Oller-Salvia, B. The Masking Game: Design of Activatable Antibodies and Mimetics for Selective Therapeutics and Cell Control. <em>ACS Cent. Sci.</em> <strong>2021</strong>, <em>7</em>, 724-738.<a href="#fnref85" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/partrita\.github\.io\/journal-club\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>